QuizandSurveyMaster/quiz_master_next

includes/qmn_help.php
includes/qmn_template_variables.php

Instead of sending email, I changed it to remote post to my contact
form. Also, fixed a minor bug that was encoding the answers in the email
preventing HTML in answers.

Converted Support Box To Remote Post Fixes #114

---

js/qmn_quiz.js
mlw_quizmaster2.php
php/about-page.php
php/admin-results-page.php
php/class-qmn-quiz-manager.php
php/class-qmn-review-message.php
php/options-page-questions-tab.php
php/quiz-options-page.php
readme.txt

* Closed Bug: Apostrophe in translation for tab name text causing errors - Issue #490
* Closed Bug: Timer resets if user copies link, opens new tab, and pastes link - Issue #489
* Closed Enhancement: Add Business, Email, And Phone To Quiz Results Search - Issue #485
* Closed Bug: "You Deserve It" button in review message leads to 404 - Issue #476
* Closed Bug: In the Hint dropdown text, the 'apostrophe' does not display properly - Issue #453

Release 4.7.8

---

css/qsm-admin.css
php/about-page.php
php/admin-results-details-page.php
php/class-qmn-quiz-manager.php
php/class-qsm-contact-manager.php
php/class-qsm-settings.php
php/quizzes-page.php
readme.txt

* Closed: Fix delete custom post types during uninstall bug ([Issue #527](https://github.com/fpcorso/quiz_master_next/issues/527))
* Closed: Change Shortcode To QSM ([Issue #515](https://github.com/fpcorso/quiz_master_next/issues/515))
* Closed: Search function for quizzes/surveys ([Issue #492](https://github.com/fpcorso/quiz_master_next/issues/492))
* Closed: Create new fields class to handle creation/post data of settings fields ([Issue #450](https://github.com/fpcorso/quiz_master_next/issues/450))
* Closed: Create new settings class to handle the settings data ([Issue #449](https://github.com/fpcorso/quiz_master_next/issues/449))
* Closed: Rewrite options system to allow for extendibility ([Issue #448](https://github.com/fpcorso/quiz_master_next/issues/448))
* Closed: Enable tabs for …

Release 5.0

---

php/question-types.php

Dynamic insertion of correct/incorrect classes for multiple choice answers doesn't work if the answer contains a ' or ". 
This works: He is barefoot
This doesn't work: He’s barefoot
Adding htmlentities to the radio button value fixes the issue.
(I'm still a fairly new contributor to OS projects, so apologies if I've done any of this wrong! Looking to learn and improve...)

Add htmlentities() to fix dynamic insertion bug

---

php/question-types.php

ISSUE:
On latest version available of quiz_master_next, if you try to validate text on other non-english language you face a validation error forcing correct answers to be added more than once. For example, if correct answer is "Atún", is necessary to add another correct answer all capitalized "ATÚN" in case user who fills the quiz use capital letters. This because to validate we transform text to uppercase letters, but this works well if you don't use special characters like "ü" or "á", and so on...
Also, when user who fills the quiz use autocorrect an extra whitespace is added and if is not deleted then answer is validated as FALSE.
SOLUTION:
1.- For uppercase letters validation replace "strtoupper" for "mb_strtoupper", that way all letters (no matter if special char or not) will be …

[Fix] Improve validation for "fill in the blank"

---

js/qsm-admin-question.js
php/admin/addons-page.php
php/admin/admin-results-page.php
php/admin/quiz-options-page.php

1. Fixed: root paragraph tag was always added into a question during switching between tinymce editor and html editor
2. Fixed: question's html isn't updated in tinymce editor if html tab was active earlier
3. Fixed default opened tab with active translations

fixed tinymce issues and default opened tab with active translations

---

php/classes/class-qsm-emails.php

Bug fix: cannot send email if "From Email" parameter is not set in QSM settings. Empty "From Email" causes incorrect header for wp_mail function.

Bug fix: cannot send email if "From Email" is not set

---

js/qsm-admin-question.js

White space at the end of text answers can lead to incorrect evaluation, as has also been reported in the answer of issue #841.
When entering/updating answers, applying `trim()` to answer strings just before saving them, can reliably prevent this issue.

trim white space of text answers

---

php/classes/class-qsm-emails.php
php/classes/class-qsm-results-pages.php

See #820 
The WYSIWYG editor is built to input HTML (or at least it converts input to HTML), so it doesn't make sense to substitute new lines with the `<br>` tag in either of these instances. It most cases, the added `<br>` tags result in broken email and results page layouts.

Removes nl2br functionality from email and results pages.

---

php/admin/settings-page.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-install.php

Introduces preferred date format settings at global and quiz which takes standard _format string_ as the input. Output of the date format question is converted to preferred date format before displaying and sending email.

Cu-bfeypn: preferred date format settings

---

php/classes/class-qsm-contact-manager.php

If user logged in and checked with yes option to disable auto fill for contact input, then the contact form input fields i.e. name and email will be blank.

Disable autofill for contact input

---

php/classes/class-qmn-quiz-manager.php

Resolve: Fatal error: PHP( 8.0.28 ) when duplicate quiz without question

---

js/qsm-admin.js
php/question-types/qsm-question-type-multiple-choice-horizontal.php
php/question-types/qsm-question-type-multiple-choice.php
php/question-types/qsm-question-type-multiple-response-horizontal.php
php/question-types/qsm-question-type-multiple-response.php
php/question-types/qsm-question-type-polar.php

added classes for image type questions

---

css/common.css
js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php
php/question-types/qsm-question-type-file-upload.php

file upload code missing

---

php/admin/functions.php
php/template-variables.php

removed the template variable of unattempted answered

---

php/admin/options-page-email-tab.php
php/admin/options-page-results-page-tab.php

update category name

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php

added login failed message

---

js/qsm-quiz.js

fixed attribute issue in shortcode

---

js/qsm-admin.js
mlw_quizmaster2.php
php/admin/options-page-questions-tab.php
php/question-types/qsm-question-title.php
php/question-types/qsm-question-type-dropdown.php
php/template-variables/qsm-tempvar-question-answers.php

Cu 85ztj975f advanced drop down function

---

php/classes/class-qmn-plugin-helper.php
php/classes/class-qsm-install.php
php/question-types/qsm-question-title.php
php/question-types/qsm-question-type-dropdown.php

added option to change deselect answer text

---

php/question-types/qsm-question-title.php
php/question-types/qsm-question-type-dropdown.php

Fixed new hook for Advance question type

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php

Cu 86795gc2y accessibility issues

---

php/classes/class-qmn-quiz-manager.php
php/shortcodes.php
php/template-variables.php
php/template-variables/qsm-tempvar-question-answers.php

Cu 86cu729j1 result page translation issue

---

js/qsm-quiz.js
mlw_quizmaster2.php
php/admin/options-page-text-tab.php
php/admin/settings-page.php
php/classes/class-qsm-fields.php
php/classes/question-types/class-question-review.php
php/question-types/qsm-question-title.php
php/template-variables.php
readme.txt

Release 18012024 QSM 8.2.2

---

php/admin/options-page-questions-tab.php
php/classes/class-qmn-quiz-creator.php
php/question-types/qsm-question-type-fill-in-the-blanks.php
php/question-types/qsm-question-type-number.php
php/question-types/qsm-question-type-paragraph.php
php/question-types/qsm-question-type-short-answer.php

Fixed inline result issue and fix phpcs issues

---

css/qsm-admin.css
js/qsm-admin.js
mlw_quizmaster2.php
php/admin/settings-page.php
php/classes/class-qsm-install.php

Cu 86cu2thhj global settings

---

php/classes/question-types/class-question-review-fill-in-blanks.php
php/question-types/qsm-question-type-fill-in-the-blanks.php
php/template-variables.php

Cu 86cuhj0h3 wpml issue fill in the blank

---

js/qsm-quiz.js
php/admin/settings-page.php
php/classes/class-qsm-install.php

added option to navigate quiz using keyboard

---

js/qsm-quiz.js

Add trigger to avoid replace Iframe src for specific case.

---

php/template-variables.php

Added roundoff feature in percentage & points variable

---

css/qsm-admin.css
js/qsm-admin.js
mlw_quizmaster2.php
php/admin/admin-results-details-page.php
php/admin/functions.php
php/admin/options-page-email-tab.php
php/admin/options-page-results-page-tab.php
php/classes/class-qsm-emails.php
php/classes/class-qsm-results-pages.php

update slash command design

---

php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-results-pages.php

fixed esc issue

---

mlw_quizmaster2.php

https://app.clickup.com/t/86cv128j5
fixed undefined constant SECURE_AUTH_COOKIE due to current_user_can function
PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /.../wp-includes/pluggable.php:929  Stack trace:  #0 /.../wp-includes/pluggable.php(694): wp_parse_auth_cookie(false, '')  #1 /.../wp-includes/class-wp-hook.php(324): wp_validate_auth_cookie(false)  #2 /.../wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)  #3 /.../wp-includes/user.php(3628): apply_filters('determine_curre...', false)  #4 /.../wp-includes/pluggable.php(70): _wp_get_current_user()  #5 /.../wp-includes/capabilities.php(877): wp_get_current_user()  #6 /.../wp-content/plugins/quiz-master-next/mlw_quizmaster2.php(172): current_user_can('manage_options')  #7 …

fixed undefined constant SECURE_AUTH_COOKIE

---

php/admin/functions.php
php/classes/class-qsm-install.php

update charset to utf8mb4_unicode_ci for emoji support

---

blocks/block.php
php/admin/functions.php
readme.txt

update changelog 9.0.1

---

php/template-variables.php

Resolve Fatal error issue when score is empty

---

mlw_quizmaster2.php
php/admin/class-failed-submission.php
php/admin/functions.php
php/classes/class-qmn-log-manager.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-install.php
readme.txt

* Added Failed submission list in QSM menu
* Added retrieve or delete failed submission
* Added admin notification if database user does not have proper permission.
* Added failed submission as post_meta in error log custom post
* On retrieve failed submission error log post status change to trash
* Check if database permission issue solved on admin_init
* If database error occurs first 15 character can be seen as error_details  in web inspector > network

Admin Notification for database permission ALTER TABLE, enable error log by default, retrieve failed submission

---

css/qsm-admin.css
js/qsm-admin.js
php/admin/class-failed-submission.php
php/classes/class-qmn-quiz-manager.php

following changes are done in submission table:
Use Ajax for action
Add column : IP, Date
Change "Retrieve" name to "Resubmit"
Add tabs of table -  Resubmit, Processed
Add checkmark on Resubmit
Show error or success message

Ajax, add date and ip column in failed submission admin dashboard table

---

js/qsm-quiz.js
php/admin/options-page-questions-tab.php

fixed enter key conflict

---

js/qsm-quiz.js
readme.txt

Fixed Missing Next button in single question quiz created with text after quiz

Fixed Missing Next button in single question quiz 

---

mlw_quizmaster2.php
readme.txt

Uncaught ReferenceError: wpApiSettings is not defined at HTMLAnchorElement. (qsm-admin.js?ver=9.0.4:1138:24) 

Fixed: wpApiSettings JS error

---

php/classes/class-qsm-emails.php
readme.txt

kses converts ampersands to &
https://core.trac.wordpress.org/ticket/11311.

Fixed: Email subject converts & to &amp;

---

php/classes/class-qsm-contact-manager.php
php/classes/class-qsm-install.php
php/classes/class-qsm-migrate.php

fixed php warning if quiz_settings are blank

---

php/admin/options-page-questions-tab.php
php/classes/question-types/class-question-review-text.php

Cu 86cv2unwj manage case sensitive inputs

---

mlw_quizmaster2.php
php/classes/class-qmn-quiz-manager.php
php/template-variables.php

Create function to check Database structure

---

js/qsm-quiz.js
php/admin/options-page-contact-tab.php
php/classes/class-qsm-contact-manager.php

added option to block domains

---

css/qsm-admin.css
js/qsm-quiz.js
mlw_quizmaster2.php
php/admin/addons-page.php
php/template-variables.php

Fixed progress bar issue with elementor popup

---

php/classes/class-qmn-quiz-manager.php

fixed conflict with advances assessment pie chard

---

css/qsm-admin.css
js/qsm-admin.js
js/qsm-quiz.js
mlw_quizmaster2.php
php/admin/addons-page.php
php/admin/functions.php
php/admin/settings-page.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-install.php
php/classes/class-qsm-tracking.php
php/template-variables.php
readme.txt

Release 9.1.2

---

php/admin/options-page-results-page-tab.php
php/admin/quiz-options-page.php
php/template-variables.php

fixed result page redirect url redirect undefined value issue

---

css/qsm-admin-question.css
php/admin/options-page-questions-tab.php
php/question-types/qsm-question-type-number.php
php/question-types/qsm-question-type-paragraph.php
php/question-types/qsm-question-type-short-answer.php

add placeholder option for paragraph

---

php/admin/options-page-questions-tab.php
php/admin/options-page-results-page-tab.php
php/shortcodes.php

fixed false result redirect page issue

---

php/admin/admin-results-details-page.php
php/admin/admin-results-page.php
php/admin/quizzes-page.php

Fixed quiz links

---

php/admin/options-page-contact-tab.php
php/classes/class-qsm-install.php
php/classes/class-qsm-settings.php

fixed issue with contact form location and hide issue

---

js/qsm-quiz.js

fix advance timer issues with qsm timer

---

php/admin/about-page.php
php/admin/addons-page.php
php/admin/admin-dashboard.php
php/admin/stats-page.php
php/admin/tools-page.php
php/rest-api.php

Cu 85ztkvkek qsm ultimate hooks

---

blocks/block.php
js/qsm-quiz.js
mlw_quizmaster2.php
php/admin/about-page.php
php/admin/addons-page.php
php/admin/admin-dashboard.php
php/admin/options-page-text-tab.php
php/admin/stats-page.php
php/admin/tools-page.php
php/classes/class-qmn-plugin-helper.php
php/classes/class-qsm-quiz-api.php
php/classes/class-qsm-results-pages.php
php/classes/class-qsm-settings.php
php/rest-api.php
php/template-variables.php
readme.txt

Release 9.2.2

---

css/qsm-admin.css
php/admin/about-page.php

UI fixes in help and system info tab

---

php/template-variables.php

Fix CONTACT_X Variable Functionality

---

css/qsm-admin.css
php/admin/functions.php

QSM 10 minor UI changes

---

js/qsm-admin.js
js/qsm-quiz.js
mlw_quizmaster2.php
php/admin/options-page-text-tab.php
php/classes/class-qsm-install.php
php/classes/class-qsm-settings.php
php/template-variables.php
readme.txt

Release QSM 9.2.3

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php

update code for qsm gamify

---

php/classes/class-qmn-quiz-manager.php

Rollback changes
