QuizandSurveyMaster/quiz_master_next

- css/qsm-admin.css
- mlw_quizmaster2.php
- php/admin/functions.php
- readme.txt
> update changelog 8.1.3

- php/classes/class-qmn-quiz-manager.php
> fixed double submit button issue

- js/qsm-quiz.js
> Fixed button issue

- php/classes/class-qsm-contact-manager.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-multiple-response-horizontal.php
- php/question-types/qsm-question-type-multiple-response.php
> Fixed issue with logic addon and required question

- js/qsm-quiz.js
- templates/qmn_primary.css
> added option to show inline result for select question type

- js/qsm-admin.js
- php/rest-api.php
> Cu 85zrupu5q correct answer import

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> added option to show inline result for fill in the blanks

- js/qsm-admin.js
- mlw_quizmaster2.php
> add question not found message in question bank

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> fixed issue with sequence correct logic

- mlw_quizmaster2.php
- readme.txt
> update changelog 8.1.5

- php/classes/class-qmn-quiz-manager.php
> Fix maximum point issue with template variable

- js/jquery.ui.slider-rtl.js
> Fixed issue polar question not working with avada theme

- php/classes/class-qmn-quiz-manager.php
> Fixed quiz not being submit

- php/admin/functions.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-multiple-response-horizontal.php
- php/question-types/qsm-question-type-multiple-response.php
>  adding labels and option border color

- php/admin/admin-results-page.php
> show screen option button only for main page

- js/qsm-quiz.js
> fixed issue with auto submit if answer wrong

- php/template-variables.php
> Fixed NA issue in correct-answer-info

- php/classes/class-qmn-quiz-manager.php
- php/classes/question-types/class-question-review-choice.php
- php/question-types/qsm-question-type-polar.php
- php/template-variables.php
> Cu 85zrxc5d5 negative score is not working

- js/qsm-quiz.js
> quiz enabled the submit quiz is wrong answer get the quizid

- php/admin/admin-dashboard.php
> fixed Visible code of Read More Text

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> fixed start quiz issue

- php/question-types/qsm-question-type-multiple-response-horizontal.php
- php/question-types/qsm-question-type-multiple-response.php
- php/template-variables.php
> add answer spaces

- js/qsm-quiz.js
> fixed issue with QuizId

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> fixed nonce validation issue

- mlw_quizmaster2.php
- php/classes/class-qsm-check-license.php
> Cu 85zrkz7c1 validate expire license message

- js/qsm-quiz.js
> Fixed result page submission time

- css/qsm-admin.css
- js/qsm-admin.js
- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-fields.php
- php/classes/class-qsm-install.php
> set seperate question limit for each category

- php/classes/class-qsm-check-license.php
- php/classes/class-qsm-install.php
- php/classes/class-qsm-settings.php
- php/template-variables.php
> Added template variables to all text fields

- css/qsm-admin.css
- js/qsm-admin.js
- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-fields.php
- php/classes/class-qsm-questions.php
> ui changes and the auto pagination fixed

- php/classes/class-qsm-fields.php
> fatal error when no categories exists

- mlw_quizmaster2.php
> showing error on missing exist class condition.

- php/classes/class-qsm-fields.php
- php/template-variables.php
> Fixed fatal error

- mlw_quizmaster2.php
> Fix include license class issue

- mlw_quizmaster2.php
- php/admin/functions.php
> Added validation to check the presence of _X minor changes

- js/qsm-admin.js
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-fields.php
>  logic of showing  questions is changed

- js/qsm-quiz.js
> added loading icon

- php/classes/class-qmn-quiz-manager.php
> Cu 85zt2a266 wporg php error

- php/classes/class-qmn-quiz-creator.php
- php/classes/class-qmn-quiz-manager.php
> Fixed error not duplicating

- js/qsm-quiz.js
> aCu 85zryjvhy inline result issue

- js/qsm-quiz.js
> fixed quiz_id js error

- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-fields.php
- php/classes/class-qsm-install.php
> fixed category limit issue

- mlw_quizmaster2.php
- php/classes/class-qsm-check-license.php
> Fix PHPCS issues

- mlw_quizmaster2.php
- php/classes/class-qsm-check-license.php
> Fixed fatel error issue with license class

- mlw_quizmaster2.php
- readme.txt
> update changelog 8.1.7

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> created new ui dashboard for show count of question status

- js/qsm-admin.js
> Fixed: accented characters are not supported in Page name.

- js/qsm-admin.js
> Fixed error in template variable starts with x

- js/qsm-quiz.js
> Add trigger 'qsm_after_loader_init' for JH project

- php/classes/class-qmn-quiz-manager.php
> Fixed issue with progress bar when limit category per questions

- php/classes/class-qmn-quiz-manager.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-multiple-response-horizontal.php
- php/question-types/qsm-question-type-multiple-response.php
> Cu 2vrt02u sapience improvements new

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-settings.php
> Cu 85zrz6zr9 submit quiz after incorrect x questions

- css/qsm-admin.css
- js/qsm-admin.js
- php/admin/options-page-email-tab.php
- php/admin/options-page-results-page-tab.php
- php/classes/class-qsm-fields.php
> UI changed QSM Admin

- css/qsm-admin.css
> Fixed the issue in QSM new footer

- js/qsm-quiz.js
> Cu 864erh837 loading gif not displayed number question type

- php/classes/class-qmn-quiz-manager.php
> update file upload error message

- css/common.css
- js/qsm-quiz.js
> update tooltip UI

- php/classes/class-qmn-plugin-helper.php
- php/classes/class-qsm-questions.php
> fixed warning wrror

- js/qsm-quiz.js
- php/admin/admin-results-page.php
> added start and end date time in result page

- js/qsm-quiz.js
- php/admin/admin-results-page.php
- php/classes/class-qmn-quiz-manager.php
> added quiz start time in result page

- mlw_quizmaster2.php
- readme.txt
> update changelog 8.1.8

- php/admin/admin-results-page.php
- php/classes/class-qmn-quiz-manager.php
- php/template-variables.php
> fixed phpcs

- php/classes/class-qmn-quiz-manager.php
Reverts QuizandSurveyMaster/quiz_master_next#2221
> Revert "Fixed issue with progress bar when limit category per questions"

- js/qsm-quiz.js
> fix number question type show inline result issue

- php/admin/admin-results-page.php
> Added some extra fileds in screen option

- php/admin/admin-results-page.php
- php/question-types/qsm-question-type-date.php
- php/question-types/qsm-question-type-dropdown.php
- php/question-types/qsm-question-type-file-upload.php
- php/question-types/qsm-question-type-fill-in-the-blanks.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-number.php
- php/question-types/qsm-question-type-opt-in.php
- php/question-types/qsm-question-type-paragraph.php
- php/question-types/qsm-question-type-short-answer.php
> replaced dot with comma

- php/admin/admin-results-page.php
- php/classes/class-qmn-quiz-manager.php
> fixed screen option issue

- php/admin/quiz-options-page.php
- php/classes/class-qsm-fields.php
- php/classes/class-qsm-settings.php
> fixed global setting issue with correct answer logic

- css/qsm-admin.css
- js/qsm-admin.js
- php/admin/options-page-email-tab.php
- php/admin/options-page-results-page-tab.php
- php/admin/quiz-options-page.php
- php/classes/class-qsm-fields.php
> New footer UI for QSM core

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
> Moved termination feature from logic addon

- css/qsm-admin.css
- js/qsm-admin.js
- php/classes/class-qsm-fields.php
> Added notices to option tab page

- css/qsm-admin.css
> fixed some css

- css/qsm-admin.css
- php/admin/options-page-email-tab.php
- php/admin/options-page-results-page-tab.php
> fixed css issue

- css/qsm-admin.css
- js/qsm-admin.js
- php/classes/class-qsm-fields.php
- php/classes/class-qsm-install.php
> New changes with JS and wrong answer field

- css/qsm-admin.css
- js/qsm-admin.js
- js/qsm-quiz.js
- php/admin/settings-page.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-fields.php
- php/classes/class-qsm-install.php
> Applied new changes for terminate quiz after x wrong answer

- js/qsm-quiz.js
> fixed sonar cloude issue

- php/admin/functions.php
> add action hook

- php/classes/class-qsm-theme-settings.php
> add hook in theme list

- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-theme-settings.php
> git commit fix issue with next button while using comment box

- js/qsm-quiz.js
> Minor changes bug fix js

- js/qsm-quiz.js
- php/classes/question-types/class-question-review-choice.php
> fix issue with mutiple correct answer logic

- mlw_quizmaster2.php
- php/admin/quizzes-page.php
- php/admin/settings-page.php
- php/classes/question-types/class-question-review-choice.php
> added option to disable public link

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
- php/template-variables.php
> New input text field for no answer in email

- php/admin/quizzes-page.php
> added option to set global setting on multiple quizzes

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> fixed comment box visible issue

- php/admin/tools-page.php
- php/classes/class-qmn-quiz-manager.php
> added audit for failed quiz result

- js/qsm-quiz.js
> Fixed timer issue in core 8.1.9

- mlw_quizmaster2.php
- readme.txt
> Fixed issue with display timer

- php/classes/class-qmn-quiz-manager.php
> Fixed issue with checkbox

- php/template-variables.php
> Fixed vulnerability issue

- js/qsm-quiz.js
> Js changes

- css/common.css
- php/classes/class-qmn-quiz-manager.php
> fixed issue with limit attempt quiz settings

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> removed decryption function

- css/common.css
- js/qsm-quiz.js
- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
- php/template-variables.php
- readme.txt
> release 8.1.11

- php/admin/options-page-style-tab.php
> Fixed No settings found msg in theme customize popup

- php/classes/class-qmn-quiz-creator.php
…ext/php/classes/class-qmn-quiz-creator.php on line 613
> Fixed: Warning: Invalid argument supplied for foreach()

- php/classes/class-qsm-emails.php
- php/classes/class-qsm-results-pages.php
> update hook for woocommerce add-on

- php/rest-api.php
- php/template-variables.php
> fix issue with result page html tags

- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
> Cu 85ztc2a57 object object error issue

- js/qsm-quiz.js
- php/classes/class-qsm-contact-manager.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-multiple-response-horizontal.php
- php/question-types/qsm-question-type-multiple-response.php
> Fixed advance question type issue and required question message bug

- js/qsm-quiz.js
> Fixed next button stuck

- js/qsm-quiz.js
> fixed issue with show inline result option

- mlw_quizmaster2.php
- readme.txt
> update changelog 8.1.12

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> fixed php sonar issue

- js/qsm-quiz.js
- php/admin/admin-results-details-page.php
- php/admin/admin-results-page.php
- php/template-variables.php
> fixed result page error

- php/classes/class-qmn-plugin-helper.php
- php/question-types/qsm-question-type-dropdown.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-multiple-response.php
- php/question-types/qsm-question-type-polar.php
> fixed issue with wpml german words

- php/classes/class-qmn-quiz-manager.php
- readme.txt
> fixed typo in changelog

- php/classes/class-qmn-log-manager.php
- php/classes/class-qsm-contact-manager.php
> fixed qsm log publically visible issue

- php/classes/class-qmn-log-manager.php
> hide qsm logs from search

- js/qsm-admin.js
- php/admin/options-page-text-tab.php
- php/admin/settings-page.php
- php/classes/class-qsm-fields.php
> added underline option in text editor

- js/qsm-quiz.js
> fixed timer showing in title after disabling timer

- js/qsm-quiz.js
- php/shortcodes.php
> fixed issue with timer popup if timer is disabled

- js/qsm-quiz.js
- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
- php/classes/question-types/class-question-review-choice.php
> added option to save unique data

- php/admin/options-page-results-page-tab.php
> added hooke qsm_result_page_before_redirect_input

- mlw_quizmaster2.php
- php/classes/class-qsm-migrate.php
- readme.txt
> release QSM 8.1.14

- js/qsm-admin.js
- js/qsm-quiz.js
> fixed sonar issue

- php/template-variables.php
> fixed Cross Site Scripting (XSS) issue with question description

- readme.txt
> update changelog date

- php/classes/class-qmn-quiz-manager.php
> fixed Button translations in WPML

- php/classes/class-qmn-quiz-manager.php
- php/template-variables.php
> fixed php warnings

- php/template-variables.php
> fix no answer provided text issue if answer is zero

- js/qsm-quiz.js
> next button not available when contact info is selected

- css/common-rtl.css
- css/qsm-admin-rtl.css
- css/qsm-admin.css
- js/qsm-quiz.js
- php/admin/quiz-options-page.php
- templates/qmn_primary.css
> Update RTL css

- css/common-rtl.css
- php/classes/class-qsm-install.php
- php/classes/class-qsm-migrate.php
> fixed result page image caption

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> fixed nonce validation  issue

- css/common.css
- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
- php/question-types/qsm-question-type-file-upload.php
> Cu 85ztu6r6y core improve messaging in file upload question

- css/common-rtl.css
- css/common.css
- php/template-variables.php
> fixed RTL issue

- php/classes/class-qmn-quiz-manager.php
> condition was wrong

- php/classes/class-qmn-quiz-manager.php
> rollback due to issues

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> Validation for the file type is done

- js/qsm-quiz.js
- php/question-types/qsm-question-type-file-upload.php
> file upload function push

- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
- php/template-variables.php
- readme.txt
> release QSM 8.1.15

- php/admin/functions.php
- php/template-variables.php
> unattempted template variable is created

- php/classes/class-qmn-quiz-manager.php
> per page timer with auto pagination

- php/classes/class-qmn-quiz-manager.php
> added random page support with manual pagination

- php/classes/class-qmn-quiz-manager.php
> added nonce validation in display_results page

- php/classes/class-qmn-quiz-manager.php
> manual pagination random questions

- php/classes/class-qmn-quiz-manager.php
- php/question-types/qsm-question-type-file-upload.php
> validation for the file upload question type

- php/template-variables/qsm-tempvar-question-answers.php
> validation for the rich type questions

- php/classes/class-qmn-plugin-helper.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
> added the meessage for the limit

- php/classes/class-qsm-install.php
> Label and tooltip is changed

- css/qsm-admin.css
> css by increasing the width of the th column

- php/classes/class-qsm-fields.php
- php/classes/class-qsm-settings.php
> Cu 85zu0byzh advance timer minute seconds option

- php/classes/class-qmn-quiz-manager.php
> Add Filter 'qsm_nonce_failed_message'

- php/template-variables.php
> Add Filter: 'qsm_questions_answers_shortcode_to_text_question'

- php/question-types/qsm-question-title.php
> Fixed question desc display html tags

- php/classes/class-qmn-quiz-manager.php
> allow support for shortcode in quiz end text

- js/qsm-admin.js
- php/admin/options-page-contact-tab.php
- php/classes/class-qsm-fields.php
> fix issue with reuired fields

- php/classes/class-qmn-quiz-manager.php
> Justhyre csic 1364

- php/classes/class-qmn-quiz-manager.php
> Fixed error while submit quiz flashcard

- js/qsm-quiz.js
> Fixed issue while changing the timer length

- php/admin/admin-results-page.php
> added option show result in admin

- css/common-rtl.css
- css/common.css
- php/classes/class-qmn-quiz-manager.php
> added alert for user if result not inserting in database

- js/qsm-admin.js
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-fields.php
- php/classes/class-qsm-install.php
> fixed category limit settings

- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
- readme.txt
> Release 8.1.18

- css/qsm-admin.css
- php/classes/class-qsm-install.php
> improve quiz option settings UI

- css/admin-dashboard-rtl.css
- css/admin-dashboard.css
- js/qsm-admin.js
- php/admin/admin-dashboard.php
- php/admin/options-page-contact-tab.php
- php/admin/options-page-questions-tab.php
- php/classes/class-qsm-migrate.php
> fixed Cross Site Request Forgery (CSRF) vulnerability

- js/qsm-admin.js
> Cu 864e8yzb2 mailerlite integration

- php/classes/class-qmn-plugin-helper.php
- php/classes/class-qmn-quiz-manager.php
- php/template-variables.php
> fixed Request header fields too large issue

- css/qsm-admin.css
- js/qsm-admin.js
- php/admin/options-page-email-tab.php
> Removed MailerLite Promo banner from email tab

- php/classes/class-qsm-emails.php
> Added hook qsm_send_result_email_before

- css/qsm-admin.css
- js/qsm-admin.js
- js/qsm-quiz.js
- php/admin/options-page-questions-tab.php
> added new timer faces and page timer settings UI

- php/admin/settings-page.php
- php/classes/class-qmn-quiz-creator.php
> Added Feature to duplicate quiz with active paid theme

- js/qsm-quiz.js
> issue to show video and image using shortcode in correct answer info

- js/qsm-quiz.js
> fixed issue with video shortcode on front end

- js/qsm-quiz.js
> Fixed single page quiz timer

- php/question-types/qsm-question-title.php
- php/question-types/qsm-question-type-fill-in-the-blanks.php
> Added hook to show select tag for fill in the blank

- php/admin/options-page-questions-tab.php
> added version compare condition for advance timer

- php/admin/options-page-style-tab.php
- php/classes/class-qmn-quiz-manager.php
> [ Issue #2412 ] Encode css & check double encoding

- css/qsm-admin-question.css
- js/qsm-admin.js
- php/admin/options-page-questions-tab.php
- php/classes/class-qsm-emails.php
> Cu 867973bnm bulk question delete

- php/question-types/qsm-question-title.php
- php/question-types/qsm-question-type-dropdown.php
- php/template-variables/qsm-tempvar-question-answers.php
> Fixed new hook parameters

- css/common-rtl.css
- css/common.css
> fixed deselect text layout issue in mobile device

- css/common-rtl.css
- css/common.css
> Revert fixed deselect text layout issue in mobile device

- php/admin/options-page-questions-tab.php
- php/admin/quiz-options-page.php
> Cu 86cu57j76 per page timer saved without license

- php/template-variables.php
> add space after comma

- php/classes/class-qmn-quiz-manager.php
> fixed JS issue with Add class for correct/incorrect answers option

- js/qsm-quiz.js
> Fixed bug with video playing

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> Fixed not pausing video on click next or previous btn click

- js/qsm-quiz.js
> Fixed disappearing issue of videopress embed video

- js/qsm-admin.js
> Added option to add code in question description

- js/qsm-admin.js
> Added hook to modify toolbar options

- css/qsm-admin-question.css
- css/qsm-admin-rtl.css
- css/qsm-admin.css
- js/qsm-admin.js
- php/admin/options-page-questions-tab.php
> added option to delete bult question

- js/qsm-quiz.js
> Fixed video playing after next/prev click

- php/question-types/qsm-question-type-dropdown.php
> Fixed warnings in advance question type due to two hooks with same name

- js/qsm-quiz.js
> Fixed audio is not paused on click of next and prev button

- php/question-types/qsm-question-title.php
> fixed code tag issue

- php/template-variables.php
> Fixed issue with sequential mode in Fill in the blank question

- js/qsm-quiz.js
> fixed issue with auto submit quiz when time over

- js/qsm-quiz.js
> Fixed advance question type compatibility with inline result

- js/qsm-quiz.js
> Changed function positions to access from addon

- php/classes/class-qmn-quiz-manager.php
> Fixed contact form pop up issue

- css/qsm-admin-question.css
- css/qsm-admin.css
- js/qsm-admin.js
- mlw_quizmaster2.php
- php/admin/options-page-email-tab.php
- php/admin/options-page-results-page-tab.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-results-pages.php
- php/classes/question-types/class-question-review.php
- readme.txt
> Cu 867968jpx email and result page redesign

- js/qsm-quiz.js
- php/admin/options-page-questions-tab.php
- php/question-types/qsm-question-type-fill-in-the-blanks.php
- php/question-types/qsm-question-type-number.php
- php/question-types/qsm-question-type-paragraph.php
- php/question-types/qsm-question-type-short-answer.php
> Added advance question setting named Minimum Characters

- php/question-types/qsm-question-type-number.php
> Fixed number type for minimum chars option

- php/question-types/qsm-question-title.php
- php/question-types/qsm-question-type-dropdown.php
- php/question-types/qsm-question-type-fill-in-the-blanks.php
> Fixed wpml issue with fill in the blank type question

- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-contact-manager.php
> fix contact multi option input WPML issue

- php/admin/addons-page.php
> Removed back button and changed header on Addon page

- php/classes/class-qmn-plugin-helper.php
> Add Filter: 'qmn_admin_results_tabs'

- js/qsm-quiz.js
- php/admin/admin-dashboard.php
> added option to navigate quiz by using keyboard

- css/qsm-admin.css
- js/qsm-admin.js
- mlw_quizmaster2.php
Added slash autosuggest command to text editor inside emails and result tab
> Template slash command

- php/template-variables.php
> Fixed question description html tags issue on userdashboard result page

- css/qsm-admin-rtl.css
- css/qsm-admin.css
- js/qsm-admin.js
- js/qsm-quiz.js
- php/admin/options-page-contact-tab.php
- php/classes/class-qsm-contact-manager.php
> added option hide form lable and add placeholder

- css/qsm-admin.css
- js/qsm-admin.js
> Template slash command : improved style, added title, improved search

- css/qsm-admin-question.css
- css/qsm-admin.css
- js/qsm-admin.js
- mlw_quizmaster2.php
- php/admin/admin-dashboard.php
- php/admin/options-page-email-tab.php
- php/admin/options-page-results-page-tab.php
- php/classes/class-qsm-contact-manager.php
- php/classes/class-qsm-emails.php
- php/classes/class-qsm-results-pages.php
> update variables tags UI

- js/qsm-admin.js
- php/classes/class-qsm-results-pages.php
- php/rest-api.php
Api call check user permission
Sanitize content on change input in editor
Sanitize content before save
Sanitize content before render
> encode result template and sanitize

- css/qsm-admin.css
- js/qsm-admin.js
- js/qsm-quiz.js
- mlw_quizmaster2.php
- php/admin/options-page-email-tab.php
- php/admin/options-page-results-page-tab.php
- php/classes/class-qsm-emails.php
- php/classes/class-qsm-results-pages.php
> added slash command to email and result template

- css/qsm-admin.css
- js/qsm-admin.js
- mlw_quizmaster2.php
- php/admin/options-page-email-tab.php
- php/admin/options-page-results-page-tab.php
> update result page UI

- css/common.css
- js/qsm-quiz.js
- php/question-types/qsm-question-type-file-upload.php
> improved file upload question UI

- css/common.css
> some css changes

- php/classes/class-qsm-emails.php
> fixed email send issue

- php/admin/functions.php
> Modified functionality to produce drop down element

- php/classes/class-qmn-quiz-manager.php
> added tranlation support

- php/classes/class-qmn-quiz-manager.php
> fixed retake button issue

- js/qsm-quiz.js
- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-creator.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-results-pages.php
- php/question-types/qsm-question-type-dropdown.php
- readme.txt
> Release QSM 8.2.3

- css/qsm-admin.css
- js/qsm-admin.js
- php/admin/settings-page.php
- php/classes/class-qsm-install.php
> update style tab design

- php/admin/functions.php
> updated extra template variables

- css/qsm-admin.css
- js/qsm-admin.js
- php/admin/settings-page.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-fields.php
- php/classes/class-qsm-install.php
> update option tab UI

- css/qsm-admin.css
- php/classes/class-qsm-install.php
> css update select logo

- php/template-variables.php
> fixed date formate issue

- css/common.css
- css/qsm-admin.css
- js/qsm-admin.js
- js/qsm-quiz.js
- mlw_quizmaster2.php
- php/admin/settings-page.php
- php/classes/class-qsm-install.php
> move global setting options

- php/classes/class-qmn-quiz-manager.php
> Added new filter for advance timer hour and minute option

- js/qsm-admin.js
- php/admin/options-page-contact-tab.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-contact-manager.php
> fixed issue with email login

- js/qsm-admin.js
> update onload js to update select labels

- php/admin/addons-page.php
> fixed all addons count

- mlw_quizmaster2.php
fixed undefined constant SECURE_AUTH_COOKIE due to current_user_can function
PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /.../wp-includes/pluggable.php:929  Stack trace:  #0 /.../wp-includes/pluggable.php(694): wp_parse_auth_cookie(false, '')  #1 /.../wp-includes/class-wp-hook.php(324): wp_validate_auth_cookie(false)  #2 /.../wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)  #3 /.../wp-includes/user.php(3628): apply_filters('determine_curre...', false)  #4 /.../wp-includes/pluggable.php(70): _wp_get_current_user()  #5 /.../wp-includes/capabilities.php(877): wp_get_current_user()  #6 /.../wp-content/plugins/quiz-master-next/mlw_quizmaster2.php(172): current_user_can('manage_options')  #7 …
> fixed undefined constant SECURE_AUTH_COOKIE 

- mlw_quizmaster2.php
- php/template-variables.php
- readme.txt
> fixed date formate with %ANSWER_X% variable

- js/qsm-quiz.js
> Add trigger : qsm_show_inline_result_after

- js/qsm-admin.js
> update condition to allow other langauge character in page name

- php/question-types/qsm-question-type-text-or-html.php
> Resolve: Youtube Iframe not working in text/html section

- php/admin/admin-results-page.php
> fixed search result issue while using special text characters

- blocks/block.php
- js/qsm-admin.js
- js/qsm-quiz.js
- mlw_quizmaster2.php
- php/admin/admin-results-page.php
- php/admin/functions.php
- php/classes/class-qsm-install.php
- php/question-types/qsm-question-type-text-or-html.php
- php/template-variables.php
- readme.txt
> Release 9.0.1

- php/classes/class-qsm-fields.php
> Cu 86cv3htcz advance timer time format admin side

- css/common.css
- js/jquery.ui.slider-rtl.js
- js/qsm-common.js
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-contact-manager.php
- php/question-types/qsm-question-type-date.php
- php/question-types/qsm-question-type-file-upload.php
- php/question-types/qsm-question-type-fill-in-the-blanks.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-multiple-response-horizontal.php
- php/question-types/qsm-question-type-multiple-response.php
- php/question-types/qsm-question-type-number.php
- php/question-types/qsm-question-type-paragraph.php
- php/question-types/qsm-question-type-short-answer.php
> Cu 86cvbnjaj accessibility issue code change

- css/qsm-admin.css
- js/qsm-admin.js
- mlw_quizmaster2.php
- php/admin/class-failed-submission.php
- php/classes/class-qmn-quiz-manager.php
- readme.txt
Added button in admin database notification to check if issue has been fixed.
> Added button in notification to check if database issue has  been fixed

- php/classes/class-qmn-quiz-manager.php
> update error message for database error during failed resubmission

- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-results-pages.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-multiple-response-horizontal.php
- php/question-types/qsm-question-type-multiple-response.php
- php/question-types/qsm-question-type-opt-in.php
- php/question-types/qsm-question-type-polar.php
- php/shortcodes.php
- php/template-variables.php
> Fix escaping sanitization quiz and result

- php/question-types/qsm-question-title.php
- php/question-types/qsm-question-type-date.php
- php/question-types/qsm-question-type-number.php
- php/question-types/qsm-question-type-paragraph.php
- php/question-types/qsm-question-type-short-answer.php
> Fixed accessibility label issue

- mlw_quizmaster2.php
- php/admin/functions.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
- php/question-types/qsm-question-title.php
> fixed migration issue for new users

- blocks/src/render.php
- mlw_quizmaster2.php
- php/admin/class-failed-submission.php
- php/classes/class-qmn-quiz-manager.php
> fixed phpcs warnings

- php/admin/options-page-questions-tab.php
- readme.txt
> Check user capabilities and input validation for delete questions

- js/qsm-quiz.js
> Cu 86cvgtuw0 quiz submits while email marked required

- php/admin/options-page-questions-tab.php
> added validation for question ids

- php/admin/options-page-questions-tab.php
> add prepare function for bulk delete question

- php/admin/options-page-questions-tab.php
> Fixed bulk delete question prepare statement

- php/classes/class-qmn-quiz-manager.php
> remove unused function delete_failed_submission

- blocks/build/answer-option/index.asset.php
- blocks/build/index.asset.php
- blocks/build/page/index.asset.php
- blocks/build/question/index.asset.php
- js/qsm-admin.js
- mlw_quizmaster2.php
- php/admin/class-failed-submission.php
- php/classes/class-qmn-quiz-manager.php
- readme.txt
> Improved notification messages for better clarity and enhanced user experience

- php/classes/class-qsm-results-pages.php
> fixed pie chart js issue

- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
> Fixed none label issue

- mlw_quizmaster2.php
- readme.txt
> update changelog 9.0.4

- php/classes/class-qsm-contact-manager.php
- php/classes/class-qsm-results-pages.php
> Fixed allowed domain validation in contact forms

- css/qsm-admin.css
> Cu 86cvpbte7 contact tab UI fix

- css/common.css
- js/qsm-admin.js
- php/classes/class-qsm-contact-manager.php
> Fix contact tab UI and behaviour

- mlw_quizmaster2.php
- readme.txt
> update changelog 9.0.5

- js/qsm-admin.js
- php/classes/class-qsm-contact-manager.php
- php/classes/class-qsm-emails.php
> fixed sonar cloud issue

- php/classes/class-qsm-questions.php
> Cu 86cvt9mpw undefined array key issue

- php/classes/class-qmn-quiz-manager.php
> adjust add result function for import results

- php/classes/class-qsm-fields.php
> Cu 86cvuadta vulnerability report

- php/classes/class-qmn-quiz-manager.php
> Fixed vulnerability

- js/qsm-admin.js
- php/classes/class-qsm-results-pages.php
> fixed vulnerability at result page

- css/qsm-admin.css
- js/qsm-quiz.js
> fixed navigation issue with single page quiz

- mlw_quizmaster2.php
> argument must be of type array or object

- js/qsm-admin.js
> Cu 86cw1n5dx some equation not rendering properly

- js/qsm-admin.js
- mlw_quizmaster2.php
- php/admin/addons-page.php
- php/classes/class-qsm-questions.php
> fixed question sorting issue

- js/qsm-admin.js
> Rollback changes

- readme.txt
> update changelog 9.1.1

- php/admin/settings-page.php
> fixed global setting issue with store data is database option

- mlw_quizmaster2.php
- php/admin/settings-page.php
- php/classes/class-qsm-tracking.php
> fixed issue with retake quiz global settings

- php/template-variables.php
> fix video tag control issue

- js/qsm-admin.js
- php/admin/options-page-contact-tab.php
- php/admin/options-page-results-page-tab.php
- php/classes/class-qsm-fields.php
- php/classes/class-qsm-results-pages.php
> Cu 85ztkvkek qsm ultimate hooks

- mlw_quizmaster2.php
- php/classes/class-qsm-fields.php
- readme.txt
> update changelog 9.1.2

- readme.txt
> add changelog text

- php/admin/options-page-results-page-tab.php
> Cu 86cujqj1x conditional shortcode and slash command

- php/shortcodes.php
> add preload for featured image

- js/qsm-quiz.js
> Fixed NaN timer issue

- php/classes/class-qmn-quiz-manager.php
> fixed issue with random order

- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
> added filter hook to update max and min points

- php/template-variables.php
> Resolve warning issue in %TIME_FINISHED% variable

- php/admin/quiz-options-page.php
> Fixed page access from url parameter changing

- mlw_quizmaster2.php
> Modify permissions for Editor role

- php/admin/admin-results-details-page.php
- php/admin/admin-results-page.php
> Fixed result page permissions for editor

- css/qsm-admin.css
> Fix Plugin css affecting Wordpress

- readme.txt
> update readme file

- mlw_quizmaster2.php
> fixed fatal error with user role

- mlw_quizmaster2.php
- readme.txt
> update changelog 9.2.1

- js/qsm-quiz.js
> Fix legacy timer count up

- php/classes/class-qsm-results-pages.php
> added index to response_data

- php/classes/class-qsm-settings.php
> Cu 86cwubxcr text before quiz show even after blank

- mlw_quizmaster2.php
> modified permission for global settings page

- php/template-variables.php
> fixed string intiger issue

- js/qsm-quiz.js
- php/template-variables.php
> Fix Completion time is doubled in user dashboard

- php/classes/class-qmn-quiz-creator.php
> updated quizID in qpages while duplicate quiz

- php/classes/class-qsm-quiz-api.php
> Added support for get quiz result by user id in APIs

- js/qsm-admin.js
- mlw_quizmaster2.php
> Fixed issue with javascript

- js/qsm-quiz.js
- mlw_quizmaster2.php
- readme.txt
> fixed arrow issue

- php/template-variables.php
> fix php Deprecated warning

- readme.txt
> update readme tested up to 6.7

- js/qsm-quiz.js
> QSM Hidden Timer Fixes

- css/qsm-admin.css
> css fixes in core

- css/admin-dashboard.css
- php/admin/admin-dashboard.php
> Cu 86cx051y6 qsm ten tabs enhancements

- php/admin/functions.php
- php/classes/class-qsm-install.php
> fixed Alter Table query issue

- php/admin/admin-dashboard.php
> fixed create quiz button visibility

- mlw_quizmaster2.php
> Fixed coflict with User Role Plugin

- php/shortcodes.php
> Replace wp kses with do shortcode

- js/qsm-quiz.js
- php/template-variables.php
> Linkedin share Feature add

- js/qsm-quiz.js
> Fix captcha issues

- js/qsm-quiz.js
> Fix minor issue in captch with rtl

- js/qsm-quiz.js
> Linkedin Share Feature Fixes

- js/qsm-quiz.js
> code modification regarding prevent progression

- js/qsm-quiz.js
> Fixed post text issue in facebook sharing

- css/qsm-admin.css
> UI fixes in template variables

- js/qsm-quiz.js
> added a trigger in timer function

- php/admin/admin-results-details-page.php
- php/shortcodes.php
> added hooks for timer new feature

- css/qsm-admin.css
- js/qsm-admin.js
- php/admin/functions.php
> global settings tab to modify theme default settings

- php/admin/options-page-questions-tab.php
> Add filter : 'qsm_question_deleted'

- php/admin/admin-results-details-page.php
> fixed warning

- php/classes/class-qmn-quiz-manager.php
> Cu 86cxf6ceh issue with view result page

- php/template-variables.php
> add hook for poll result

- php/question-types/qsm-question-title.php
- php/question-types/qsm-question-type-dropdown.php
> fixed inline drop down not showing issue

- php/template-variables/qsm-tempvar-question-answers.php
> fixed inline drop down multiple

- js/qsm-quiz.js
- php/admin/settings-page.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
> added option to do not scroll on result page

- php/classes/class-qsm-questions.php
> fixed issue with question publish condition

- css/common-rtl.css
> fix right/wrong indicators overlaping for rtl sites

- css/common-rtl.css
> Cu 86cy1jafp fix right/wrong indicatiors for rtl site

- php/admin/options-page-style-tab.php
> change hook placement

- css/qsm-admin.css
> fix help slide issues in about section

- mlw_quizmaster2.php
> Fixed permission for create quiz page

- php/classes/class-qsm-tracking.php
> fixed JS sql query error

- php/admin/admin-dashboard.php
- php/admin/functions.php
- php/admin/options-page-email-tab.php
- php/admin/options-page-results-page-tab.php
> fixed issue with parsing load script

- js/qsm-admin.js
> Fixed issue with closing popup message issue

- css/qsm-admin.css
- js/qsm-admin.js
> Minor css changes and fixed sonar cloud issues

- css/qsm-admin.css
- php/admin/admin-dashboard.php
- php/admin/create-quiz-page.php
- php/admin/functions.php
- php/admin/options-page-style-tab.php
> fixe sonar and phpcs issue

- php/admin/functions.php
> hide theme default tab if no any theme active

- css/admin-dashboard-rtl.css
- css/admin-dashboard.css
- css/qsm-admin.css
- js/qsm-admin.js
- mlw_quizmaster2.php
- php/admin/admin-dashboard.php
- php/admin/functions.php
- readme.txt
> fixed issue with warning popup and change log section

- php/admin/functions.php
> fixed sonar clounde issue

- readme.txt
> update QSM demo video link

- php/admin/admin-results-page.php
- php/admin/tools-page.php
> Cu 86cxre45n fixed db storage issues for deletion

- php/admin/tools-page.php
> Minor chnages

- php/classes/class-qsm-check-license.php
> Change sslverify settings

- php/admin/tools-page.php
> Fixed issue with delete all question button

- js/qsm-admin.js
> Fixed issue with multiple alerts

- php/admin/admin-results-page.php
- php/admin/tools-page.php
> Fixed phpcs issue and added description if question title is empty

- js/qsm-admin.js
> Fixed issue with display email template

- php/admin/functions.php
> Add %QUESTION_ANSWER_ATTEMPTED% variable in qsm

- php/classes/class-qmn-quiz-manager.php
> added server side validation for contact form

- js/qsm-quiz.js
> add variable to use the user response

- js/qsm-quiz.js
- php/template-variables.php
> user_answer variable fixs on result page

- templates/qmn_primary.css
> fix text color issue on dark theme

- php/template-variables.php
> Fix warnings and errors

- js/qsm-quiz.js
> user_answer variable fixes

- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
- php/template-variables.php
- readme.txt
> release QSM 10.1.0

- php/admin/settings-page.php
- php/classes/class-qmn-quiz-manager.php
- php/question-types/qsm-question-title.php
- php/shortcodes.php
> Cu 85zte5q3u add global option to preload featured image

- css/common.css
- js/qsm-quiz.js
- php/admin/settings-page.php
- php/question-types/qsm-question-title.php
> update js logic to skip tab loop

- php/admin/functions.php
- php/admin/options-page-email-tab.php
> Remove advance certificate code

- php/template-variables.php
> added hook for audio answer type question

- css/qsm-admin-question.css
- js/qsm-admin.js
- php/admin/options-page-questions-tab.php
- php/rest-api.php
> Cu 86cyq3zz9 search question from question type

- js/qsm-quiz.js
> prevent quiz from reload

- php/template-variables.php
> fix user answer variable issue

- css/qsm-admin.css
> Fix popup UI

- assets/blueprints/blueprint.json
- css/qsm-admin-question.css
- css/qsm-admin.css
- js/qsm-admin.js
- php/admin/options-page-questions-tab.php
> update add and remove answer UI

- php/classes/class-qsm-results-pages.php
> Allowed template variables in result page condition value

- css/qsm-admin-question-rtl.css
- css/qsm-admin-question.css
- css/qsm-admin.css
- js/qsm-admin.js
- php/admin/options-page-questions-tab.php
- php/rest-api.php
- php/template-variables.php
> imoprove UI question button

- php/template-variables/qsm-tempvar-question-answers.php
> add filter for after result submission answers

- php/admin/options-page-questions-tab.php
- php/classes/class-qmn-plugin-helper.php
- php/question-types/qsm-question-type-dropdown.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-multiple-response-horizontal.php
- php/question-types/qsm-question-type-multiple-response.php
> Added option to set answer limit

- php/classes/class-qmn-plugin-helper.php
- php/classes/class-qmn-quiz-manager.php
- php/question-types/qsm-question-type-dropdown.php
- php/question-types/qsm-question-type-multiple-choice-horizontal.php
- php/question-types/qsm-question-type-multiple-choice.php
- php/question-types/qsm-question-type-multiple-response-horizontal.php
- php/question-types/qsm-question-type-multiple-response.php
- php/template-variables.php
> Fixed answer limit option for result page

- php/classes/class-qmn-quiz-manager.php
> Fixed duplicate result entry issue

- css/qsm-admin-question.css
> Fix height issue of question bank

- js/qsm-admin.js
> fixed add answer field issue

- js/qsm-admin.js
> Fixed answer template issue

- php/admin/admin-results-page.php
> Cu 86czdd4u9 quiz proctor addon adjust code

- js/qsm-admin.js
- php/admin/functions.php
> Fixed nonce validation and vulnerability issue

- php/template-variables.php
> Fixed display question counter issue on result page while using export results as pdf

- mlw_quizmaster2.php
- readme.txt
> update changelog 10.2.3

- php/classes/class-qmn-quiz-manager.php
> Cu 86czn8xhr advance question maximum point issue

- js/qsm-admin.js
> Fixed reload page issue while deleting question

- php/admin/options-page-email-tab.php
> add documentation for template variables

- js/qsm-quiz.js
- php/classes/class-qmn-plugin-helper.php
- php/classes/class-qmn-quiz-manager.php
> Fixed issues with email limit option

- php/classes/class-qmn-plugin-helper.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
- php/classes/class-qsm-settings.php
> Removed unused text field option

- mlw_quizmaster2.php
- readme.txt
> Release 10.2.4

- php/classes/class-qsm-results-pages.php
> register and add language support for redirect url

- mlw_quizmaster2.php
- php/admin/admin-dashboard.php
- php/admin/admin-results-page.php
- php/admin/quiz-options-page.php
- php/classes/class-qmn-plugin-helper.php
- php/classes/class-qsm-install.php
- php/classes/class-qsm-questions.php
- php/classes/class-qsm-results-pages.php
- php/template-variables.php
- readme.txt
> Release 10.2.5

- php/template-variables.php
> fixed PHP Object Injection vulnerability

- php/template-variables.php
> fixed sonar Claude issue

- php/classes/class-qsm-emails.php
> Cu 86d010hx4 add variable in to field email

- js/qsm-quiz.js
- php/classes/class-qmn-quiz-manager.php
> Fixed pagination issue

- css/common-rtl.css
- css/common.css
- js/qsm-quiz.js
- php/question-types/qsm-question-type-file-upload.php
- php/template-variables.php
> Cu 86czwtp01 display snapshot and activated addons first

- css/admin-dashboard-rtl.css
- css/admin-dashboard.css
- css/qsm-admin.css
- php/admin/admin-dashboard.php
> Added recent section on the QSM dashboard page

- css/common-rtl.css
- css/common.css
- js/qsm-quiz.js
- mlw_quizmaster2.php
- php/classes/class-qmn-quiz-manager.php
- php/classes/question-types/class-question-review-file-upload.php
- php/question-types/qsm-question-type-file-upload.php
- readme.txt
> Fixed JS conflict of file upload with Themes

- php/classes/class-qmn-quiz-manager.php
> Fixed contact form error

- php/classes/class-qmn-quiz-manager.php
- php/classes/class-qsm-install.php
> removed randomise page option

- php/classes/class-qmn-quiz-manager.php
> Fixed issue with Limit submissions based on email address

- readme.txt
> update changelog 10.2.8
