QuizandSurveyMaster/quiz_master_next

includes/qmn_quiz.php
includes/qmn_template_variables.php
mlw_quizmaster2.php

Turned the shortcode function into the Quiz Manager class.

Divided Quiz File Resolves #80

---

includes/js/qmn_quiz.js
includes/qmn_quiz.php

Added radio and checkboxes to the required system.

Enhanced Required System Resolves #98

---

uninstall.php

Added check to ensure file was not called directly and cleaned up the
code a bit.

Added Uninstall Check Fixes #111

---

includes/qmn_global_settings.php
includes/qmn_usage_tracking.php
mlw_quizmaster2.php

Also created new global settings page so user can turn on usage tracker.

Created Initial Usage Tracker

---

includes/qmn_helper.php
includes/qmn_options_style_tab.php
includes/qmn_quiz.php
includes/qmn_quiz_creator.php

Added a new class to the comment section.

Updated Default Style

---

includes/qmn_global_settings.php
includes/qmn_quiz_admin.php
includes/qmn_quiz_creator.php
includes/qmn_tools.php
includes/qmn_update.php
mlw_quizmaster2.php

This adds the functions to create custom post types for the quizzes. With this update, admins will now see quizzes have individual urls that they can add to their menus or create archives of.

Added Initial CPT Functions

---

js/qmn_pagination.js
mlw_quizmaster2.php
php/qmn_credits.php
php/qmn_quiz.php
php/qmn_quiz_creator.php
php/qmn_results_details.php
php/qmn_usage_tracking.php
readme.txt

Release 4.3.1

---

js/qmn_pagination.js
php/qmn_quiz.php

Fixed Eliminates first page if empty

Fixed Eliminates first page if empty

---

php/qmn_options_email_tab.php
php/qmn_options_results_page_tab.php
php/qmn_options_text_tab.php
php/qmn_template_variables.php

Added a template variable so that the timer for the quiz can be shown in
minutes.

Made a new template variable %TIMER_MINUTES%

---

php/qmn_addons.php
php/qmn_adverts.php
php/qmn_alerts.php
php/qmn_credits.php
php/qmn_dashboard_widgets.php
php/qmn_help.php
php/qmn_leaderboard.php
php/qmn_options_certificate_tab.php
php/qmn_options_email_tab.php
php/qmn_options_leaderboard_tab.php
php/qmn_options_option_tab.php
php/qmn_options_preview_tab.php
php/qmn_options_questions_tab.php
php/qmn_options_results_page_tab.php
php/qmn_options_style_tab.php
php/qmn_options_text_tab.php
php/qmn_options_tools_tab.php
php/qmn_question_types.php
php/qmn_quiz_admin.php
php/qmn_quiz_install.php
php/qmn_quiz_options.php
php/qmn_results.php
php/qmn_results_details.php
php/qmn_template_variables.php
php/qmn_tools.php
php/qmn_update.php
php/qmn_widgets.php

This contains updates to the documentation for the plugin.

PHP file documentation

---

js/qmn_pagination.js
php/qmn_quiz.php

Adds a span element between the previous and next buttons that shows which page the user is on and how many total pages are in the quiz.

Adds text on quiz to show which page the user is on

---

js/admin_question.js
php/qmn_options_questions_tab.php

Adds ability to drag and drop questions to re-order them

---

mlw_quizmaster2.php
php/qmn_credits.php
php/qmn_options_text_tab.php
php/qmn_options_tools_tab.php
readme.txt

* Security Fix: Fixed possible sql injection from authenticated users on text and tools tabs

Security Release 4.2.3

---

css/qmn_admin.css
mlw_quizmaster2.php
php/qmn-stats-page.php
php/qmn_credits.php
php/qmn_help.php
php/qmn_leaderboard.php
php/qmn_options_certificate_tab.php
php/qmn_options_email_tab.php
php/qmn_options_leaderboard_tab.php
php/qmn_options_option_tab.php
php/qmn_options_questions_tab.php
php/qmn_options_results_page_tab.php
php/qmn_options_style_tab.php
php/qmn_options_text_tab.php
php/qmn_options_tools_tab.php
php/qmn_question_types.php
php/qmn_quiz.php
php/qmn_quiz_admin.php
php/qmn_quiz_creator.php
php/qmn_results.php
php/qmn_results_details.php
php/qmn_widgets.php
readme.txt

* Security Fix: Fixed possible sql injection from authenticated users on certificate, email, and leaderboard tabs
* Security Fix: Fixed data validation bug on help page, leaderboard shortcode, and quiz shortcode

Security Release 4.4.4

---

mlw_quizmaster2.php
php/qmn_credits.php
php/qmn_options_questions_tab.php
readme.txt

* Fixes parse error on hosts with older PHP versions

Bugfix 4.5.1

---

js/qmn_pagination.js
js/qmn_quiz.js
js/qmn_timer.js
php/class-qmn-quiz-manager.php

This newer version allows the plugin to submit the quiz/survey using ajax and display the results page without reloading the page. This also fixes the redirect bug.

AJAX Submission Of Quiz/Survey

---

mlw_quizmaster2.php
php/class-qmn-quiz-manager.php
php/class-qmn-tracking.php
readme.txt

* Bug fix for browsers with JavaScript turned off

Release 4.6.2

---

css/qmn_admin.css
js/qmn_quiz.js
mlw_quizmaster2.php
php/about-page.php
php/class-qmn-quiz-manager.php
php/question-types.php
php/quizzes-page.php
readme.txt
templates/qmn_amethyst.css
templates/qmn_emerald.css
templates/qmn_gray.css
templates/qmn_primary.css
templates/qmn_turquoise.css

* Fixes timer bug that caused the timer to continue counting down after quiz has been submitted
* Fixes theme conflict between QSM and some Bootstrap based themes
* Fixes Quizzes/Surveys page table width issue
* Fixes but preventing editing of quiz post settings
* Minor design changes

Release 4.6.5

---

js/qmn_quiz.js
mlw_quizmaster2.php
php/about-page.php
readme.txt

* Fixes bug preventing some users to not be able to submit quiz
* Fixes bug causing undefined titles for some users

Release 4.6.6

---

php/class-qmn-plugin-helper.php
php/options-page-option-tab.php

Adds the ability to randomize just the answers in a quiz or survey based on issue #330

Adds ability to randomize only answers

---

js/qmn_quiz.js
php/question-types.php

Adds the default option for drop downs and adds necessary code to js
file for required questions

Adds default drop down option for issue #334

---

php/about-page.php
php/class-qsm-changelog-generator.php

Creates a class that calls the GitHub API and retrieves the closed
issues for a certain milestone.

Creates GitHub changelog generator class

---

js/qmn_quiz.js
templates/qmn_amethyst.css
templates/qmn_base.css
templates/qmn_emerald.css
templates/qmn_gray.css
templates/qmn_primary.css
templates/qmn_turquoise.css

Adds new spinner/disables submit button

---

js/qmn_quiz.js
mlw_quizmaster2.php
php/about-page.php
readme.txt

* Closed Bug: Multiple quizzes on page causes plugin to scroll to top quiz when submitting - Issue #428

Release 4.7.2

---

mlw_quizmaster2.php
php/about-page.php
php/class-qmn-quiz-manager.php
php/options-page-questions-tab.php
readme.txt

* Closed Enhancement: Create new question section id CSS class for each question - Issue #440
* Closed Bug: Creating/Editing questions throw PHP notice of undefined index - Issue #436

Release 4.7.3

---

mlw_quizmaster2.php
php/about-page.php
php/class-qmn-quiz-manager.php
php/quizzes-page.php
readme.txt

* Closed Bug: Results page will not load on some sites - Issue #445

Release 4.7.4

---

mlw_quizmaster2.php
php/about-page.php
php/options-page-certificate-tab.php
php/question-types.php
readme.txt

* Closed Enhancement: Change Text Block To Text/HTML - Issue #451
* Closed Enhancement: Create alert warning about removal of certificate - Issue #382

Release 4.7.5

---

CHANGELOG.md
mlw_quizmaster2.php
php/about-page.php
php/class-qmn-tracking.php
php/class-qsm-install.php
php/settings-page.php
readme.txt
uninstall.php

* Closed: Add language and error logs to usage tracking - Issue #457

Release 4.7.6

---

php/admin-results-page.php

Restore the default WordPress font size for the table along with default WordPress link behavior and some formatting fixes.

Restore Default WordPress Styling.

---

mlw_quizmaster2.php
php/about-page.php
php/class-qmn-quiz-manager.php
php/class-qmn-tracking.php
readme.txt

* Closed Bug: From Email Bug Causing 500 Error On WP 4.6 - Issue #473
* Closed Enhancement: Table Styles Don't Match Default WordPress Styles. - Issue #471
* Closed Bug: Tracking manager causes admin server error when request error occurs. - Issue #470

Release 4.7.7

---

CHANGELOG.md
mlw_quizmaster2.php
php/about-page.php
php/options-page-questions-tab.php
readme.txt

* CSRF vulnerability on Questions tab Issue #499

Release 4.7.9

---

CHANGELOG.md
js/qsm-admin-question.js
mlw_quizmaster2.php
php/about-page.php
php/class-qmn-tracking.php
php/class-qsm-install.php
php/quizzes-page.php
php/settings-page.php
readme.txt

* Closed Bug: Edit question not working when visual editor is off - Issue #497
* Closed Bug: Localization incomplete on Global Settings page - Issue #478

Release 4.7.10

---

mlw_quizmaster2.php
php/about-page.php
php/class-qsm-contact-manager.php
readme.txt

* Closed Bug: The setting to hide contact fields from logged-in users is hiding fields from visitors too Issue #535

Release 5.0.1

---

mlw_quizmaster2.php
php/about-page.php
php/class-qmn-tracking.php
php/help-page.php
php/template-variables.php
readme.txt

* Closed Bug: Social sharing text not updating when user changes the text ([Issue #541](https://github.com/fpcorso/quiz_master_next/issues/541))

Release 5.0.2

---

CHANGELOG.md
js/qmn_quiz.js
mlw_quizmaster2.php
php/about-page.php
php/adverts-generate.php
php/class-qmn-log-manager.php
php/class-qmn-quiz-manager.php
readme.txt

* Closed Bug: Required fields are not checked 2nd time user takes quiz when timer is turned on ([Issue #528](https://github.com/fpcorso/quiz_master_next/issues/528))
* Closed Enhancement: Ensure compatibility with WordPress 4.8 ([Issue #554](https://github.com/fpcorso/quiz_master_next/issues/554))

5.0.4 Release

---

mlw_quizmaster2.php
php/about-page.php
php/class-qmn-quiz-manager.php
php/help-page.php
php/options-page-leaderboard-tab.php
php/stats-page.php
readme.txt

* Closed Enhancement: Add notice for leaderboard removal - ([Issue #562](https://github.com/fpcorso/quiz_master_next/issues/562))
* Closed Bug: Scheduled timeframe options are not working - ([Issue #558](https://github.com/fpcorso/quiz_master_next/issues/558))

5.0.5 Release

---

mlw_quizmaster2.php
php/about-page.php
php/question-types.php
readme.txt

* Closed Bug: HTML Entities causing incorrect answers and missing user answer - ([Issue #565](https://github.com/fpcorso/quiz_master_next/issues/565))

5.0.6 Release

---

js/qsm-admin.js
mlw_quizmaster2.php
php/about-page.php
php/class-qmn-quiz-creator.php
php/options-page-questions-tab.php
php/quiz-options-page.php
readme.txt

* Closed Bug: Answers of "0" disappear when adding or editing questions - ([Issue #531](https://github.com/fpcorso/quiz_master_next/issues/531))

Release 5.0.7

---

CHANGELOG.md
css/qsm-admin-question.css
js/qsm-admin.js
mlw_quizmaster2.php
php/about-page.php
php/admin-results-page.php
php/class-qmn-log-manager.php
php/class-qmn-plugin-helper.php
php/class-qmn-quiz-creator.php
php/class-qmn-quiz-manager.php
php/class-qsm-fields.php
php/dashboard-widgets.php
php/options-page-questions-tab.php
php/quizzes-page.php
php/shortcodes.php
php/template-variables.php
php/widgets.php
readme.txt

* Closed Enhancement: Add all active quizzes function to API - ([Issue #552](https://github.com/fpcorso/quiz_master_next/issues/552))
* Closed User Request: Shortcode or variable for dynamic link to specific quiz/survey - ([Issue #524](https://github.com/fpcorso/quiz_master_next/issues/524))
* Closed Enhancement: Use locale's date to generate date strings - ([Issue #479](https://github.com/fpcorso/quiz_master_next/issues/479))
* Closed User Request: Allow users to change the date to European Date DD.MM.YYYY - ([Issue #439](https://github.com/fpcorso/quiz_master_next/issues/439))
* Closed User Request: More Space in the Correct Answer Info textbox - ([Issue #417](https://github.com/fpcorso/quiz_master_next/issues/417))

Release 5.1.0

---

ISSUE_TEMPLATE.md
mlw_quizmaster2.php
php/about-page.php
php/class-qmn-quiz-manager.php
php/options-page-questions-tab.php
php/quiz-options-page.php
readme.txt

* Closed Bug: MathJax library not loading - ([Issue #590](https://github.com/fpcorso/quiz_master_next/issues/590))
* Closed Bug: Fatal error: Call to a member function register_question_type - ([Issue #509](https://github.com/fpcorso/quiz_master_next/issues/509))

5.1.3 Release

---

mlw_quizmaster2.php
php/about-page.php
php/addons-page.php
php/class-qmn-quiz-manager.php
readme.txt

* Closed Bug: Headers already sent message - ([Issue #596](https://github.com/fpcorso/quiz_master_next/issues/596))
* Closed Bug: Styling for hints is missing causing them to be hard to read - ([Issue #587](https://github.com/fpcorso/quiz_master_next/issues/587))

5.1.4 Release

---

mlw_quizmaster2.php
php/class-qmn-quiz-manager.php
readme.txt

* IMPORTANT FIX: 5.1.4 had a fatal error for sites using out of date PHP versions. Please update to this!

5.1.5 Release

---

mlw_quizmaster2.php
php/about-page.php
php/class-qmn-quiz-manager.php
php/class-qsm-contact-manager.php
readme.txt

* Closed Bug: Timezone ID '' is invalid - ([Issue #606](https://github.com/fpcorso/quiz_master_next/issues/606))
* Closed Bug: Required contact fields not working correctly when the loggedin_user_contact option is set to no - ([Issue #603](https://github.com/fpcorso/quiz_master_next/issues/603))

5.1.6 Release

---

css/qsm-admin.css
js/qsm-admin.js
mlw_quizmaster2.php
php/about-page.php
php/adverts-generate.php
php/class-qmn-quiz-creator.php
php/class-qsm-fields.php
php/class-qsm-settings.php
php/quizzes-page.php
readme.txt

* Closed Bug: Quizzes/Surveys table not working on certain installs - ([Issue #598](https://github.com/fpcorso/quiz_master_next/issues/598))

5.1.7 Release

---

mlw_quizmaster2.php
php/admin/admin-results-details-page.php
php/admin/admin-results-page.php
php/admin/options-page-email-tab.php
php/classes/class-qmn-tracking.php
readme.txt

* Makes minor style adjustments
* Adds additional hook to admin results details page
* Modifies a few error messages

Release 5.2.2

---

js/qsm-admin-question.js
mlw_quizmaster2.php
php/admin/about-page.php
php/admin/admin-results-details-page.php
php/admin/quizzes-page.php
php/rest-api.php
readme.txt

* Closed Bug: Cannot save question on certain servers - ([Issue #651](https://github.com/fpcorso/quiz_master_next/issues/651))
* Closed Bug: Questions/Answers Template Not Loaded In Admin Results Page - ([Issue #636](https://github.com/fpcorso/quiz_master_next/issues/636))

5.2.3 Release

---

js/qmn_quiz.js
mlw_quizmaster2.php
php/admin/about-page.php
php/admin/admin-results-page.php
php/admin/help-page.php
php/classes/class-qsm-contact-manager.php
php/gdpr.php
readme.txt
templates/qmn_amethyst.css
templates/qmn_base.css
templates/qmn_emerald.css
templates/qmn_gray.css
templates/qmn_primary.css
templates/qmn_turquoise.css

* Closed Enhancement: Add user ID to admin results page table - ([Issue #682](https://github.com/fpcorso/quiz_master_next/issues/682))
* Closed Enhancement: Integrate with WordPress 4.9.6 GDPR features - ([Issue #681](https://github.com/fpcorso/quiz_master_next/issues/681))

Release 5.3.1

---

js/qmn_quiz.js
mlw_quizmaster2.php
php/admin/about-page.php
php/classes/class-qmn-quiz-manager.php
readme.txt
templates/qmn_amethyst.css
templates/qmn_base.css
templates/qmn_emerald.css
templates/qmn_gray.css
templates/qmn_primary.css
templates/qmn_turquoise.css

* Closed Plugin Compatibility: Conflict with Divi Builder ([Issue #686](https://api.github.com/repos/fpcorso/quiz_master_next/issues/686))

Release 5.3.2

---

mlw_quizmaster2.php
php/admin/help-page.php
php/admin/options-page-contact-tab.php
php/admin/options-page-email-tab.php
php/admin/options-page-preview-tab.php
php/admin/options-page-questions-tab.php
php/admin/options-page-style-tab.php
php/admin/quizzes-page.php
php/classes/class-qsm-install.php
readme.txt

* Changes links from old documentation to newer documentation

6.0.4 Release

---

php/admin/quizzes-page.php
php/classes/class-qmn-quiz-manager.php
php/question-types.php

#1hrxev - Solved rich text answer math equation issue

#1vj7a5 - Added import and export button in quiz index page

---

php/admin/addons-page.php

Change sendy to sendinblue - #27h4rj

Change text in Get a Free Addon - #27h9qw

---

css/jquery-ui.css
php/question-types.php
php/template-variables.php

Issue - Hint not readable - #29rfer
Issue - Full html of the option is being output in the ID of wrapper div and in the value of the option: - #2bk78p

Issue - QSM not picking up user select answer - #21nudq

---

css/common.css
js/qsm-admin-question.js
js/qsm-quiz.js
mlw_quizmaster2.php
php/admin/functions.php
php/admin/options-page-questions-tab.php
php/classes/class-qsm-install.php
php/question-types.php
readme.txt

-Take to quiz edit after creating a new quiz - #27jj26
-Can you please add 'deselect answer' button?? - #1knw51
-Changed the version and added the changelog

-Adding  questions from question  bank - #23tact

---

mlw_quizmaster2.php
php/admin/functions.php
php/admin/quiz-options-page.php
php/admin/quizzes-page.php
php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-creator.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-contact-manager.php
php/classes/class-qsm-install.php
php/question-types.php

Special capabilities #810 - #1trk1c
Phone number field validation - #2dtaag
JQuery UI error - #2dn4ah
Customize text using the "Text tab" and remove from "Options Tab"- #2fmum4
Solved the youtube link not converting into video issue

First commit of QSm 6.4.6

---

css/show-js-error.css
js/qsm-quiz.js
js/show-js-error.custom.js
php/admin/functions.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-contact-manager.php

Solved phone validation issue - #2dtaag

Added JS Error library - #29hkzb

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-install.php
php/shortcodes.php

Solved database type issue - #2dnvp4

---

js/qsm-quiz.js
php/admin/admin-results-page.php
php/shortcodes.php

Added option to delete the result permanent - #2fmcpd

JS Error - Remove github link, change text - #2nmbc0

---

js/admin.js
js/qsm-quiz.js
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php

Created backend for catergory selection in random question - #2hrpe7

Fixed the advanced timer issue - #2fp5ux

---

css/common.css
php/classes/class-qmn-quiz-manager.php

Solved Checkbox overriding text issue - #2qpmck

Solved quote issue in custom css - #2kr6tc

---

php/classes/class-qmn-quiz-manager.php
php/shortcodes.php

"Time is up" message coming on the quiz  - #2tq0wx

"This quiz is for logged in users only" appears twice - #2tq5dj

---

js/jquery-ui.js
mlw_quizmaster2.php
php/classes/class-qmn-quiz-manager.php
readme.txt

- Removed the external link of js and added the js file in plugin

---

php/classes/class-qmn-quiz-manager.php

Filter to add additional data to email content

---

php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-questions.php
php/template-variables.php

Fixed Spaces added before tables in questions - #2vrmxz
Changed the is_active_plugin function with our own function - #2xpgh2

Fixed youtube embeded not showing on result page

---

php/admin/functions.php

Bug 35pg77 fix

---

js/qsm-quiz.js

Updated the logic used for validating email by building a new function named isEmail- bug/37tnwx( Issue With Email Field)

Updated the email validation login - bug/37tnwx

---

js/qsm-quiz.js

Time to complete not measured when Retaking Quiz Fix bug/31rn5f

---

js/qsm-quiz.js

Bug ID: bug/39pnaj
Bug Desc: Time up popup not working properly with retake quiz button.
Status: Fixed

Time up popup not working properly with retake quiz button - bug/39pnaj

---

php/classes/class-qmn-quiz-manager.php
php/classes/class-qmn-review-message.php

Bug ID: CU-39qwub
Bug Desc: Plugin gets results from db on every screen
Status: Fixed

Plugin gets results from db on every screen Fix - bug/CU-39qwub

---

php/admin/functions.php
php/question-types.php
uninstall.php

Task ID: bug/CU-35k3wa
Desc: Fill in the blank type question not appearing
Status: Fixed for both old and current version.

Fix for Fill in the blank type question not appearing - bug/CU-35k3wa

---

css/common.css
php/question-types.php

Fixed the inconsistent title for polar question type.

Fix for inconsistent polar question type

---

js/qsm-quiz.js

Fix for recaptcha appearing on all quiz pages.

Recaptcha add on fix

---

css/admin-dashboard.css
css/qsm-admin.css
php/admin/admin-dashboard.php
php/admin/options-page-email-tab.php
php/admin/options-page-results-page-tab.php

Change the wizard accordion arrow
Change the box shadow and width of email and result page
Show only five changelog with read more link

QSM Polishing

---

css/admin-dashboard.css
css/qsm-admin-question.css
css/qsm-admin.css
js/qsm-admin-emails.js
js/qsm-admin-question.js
js/qsm-admin-results.js
php/admin/addons-page.php
php/admin/admin-dashboard.php
php/admin/functions.php
php/admin/options-page-email-tab.php
php/admin/options-page-questions-tab.php
php/admin/options-page-results-page-tab.php
php/admin/stats-page.php
php/classes/class-qsm-install.php

polar question confusion
Enable change of answer (change text and options accrodingly)
tooltip font and cutting
[esc] with close button
remove loading alert box in results/email
minutes with time field
max width for popup
remove background from addons page titles
Fixed stat page issue

QSM Polishing:

---

css/qsm-admin-question.css
js/qsm-admin-question.js
js/qsm-quiz.js
php/admin/options-page-questions-tab.php
php/classes/class-qmn-quiz-manager.php
templates/qmn_primary.css

Hide Previous button for pages - #3kmtej …
Per page timer support for Advanced Timer- #3nm2ba
Change icon & link title - #3kmt92

Hide Previous button for pages - #3kmtej

---

php/admin/admin-results-page.php
php/admin/options-page-questions-tab.php
php/template-variables.php

- Changed questions options doc limk

---

php/classes/class-qmn-quiz-manager.php

CU-13dfkw - Add paramters and timstamp in google sheets for quiz

CU-13dfkw Add paramters and timstamp in google sheets for quiz

---

css/qsm-admin-question.css
js/qsm-admin-question.js
php/admin/options-page-questions-tab.php

Fixed short answer checking issue - CU-13e63w
Hide Description by default - CU-13cf45

Fixed Can't add answers to Small/Large Open Answer Question types issue - CU-3tr5hz 

---

js/qsm-quiz.js
php/classes/class-qsm-settings.php
php/template-variables.php

CU-31rnt0 - Required field hidden by the conditional logic is still required

CU-31rnt0[qa] - Required field hidden by the conditional logic

---

php/classes/class-qmn-quiz-manager.php

Reporting and analysis version 1.3.6

CU-2xrtp4[qa] - Reporting and analysis version 1.3.6

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php
php/question-types.php

- File upload loading gif added to indicate file is being uploading.

CU-3vqhe8 - Nothing gets displayed for File Upload type question fixed

---

css/qsm-admin.css
php/admin/addons-page.php
php/admin/admin-dashboard.php

- Added utm link into addon url

CU-23mqja - Fixed sidebar design issue in addon page

---

php/classes/class-qmn-quiz-manager.php

Fixed HTML/CSS validation issues

CU-3qkcwt - Fixed HTML/CSS validation issues

---

php/question-types.php
php/shortcodes.php

Change main tags with div which show validations errors.
Remove white space in id for answer container.

CU-3qkcwt - [Simple Popup] - validation issues fixed

---

php/admin/addons-page.php
php/admin/admin-dashboard.php

- Make core compatible with new parsing script and old script 
- Still need to change the URL

- Removed the transient from parsing script 

---

php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-contact-manager.php
php/shortcodes.php

CU-3qkcwt - [Simple Popup] - validation issue, all issues fixed

---

php/classes/class-qmn-quiz-manager.php

PHP warning when submitting the result - fixed

CU-15dppk - PHP warning when submitting the result - fixed

---

php/classes/class-qmn-quiz-manager.php

CU-176zez - Big Problem with scoring - Fixed

---

css/qsm-admin.css
php/admin/admin-results-details-page.php

Fixed name and email were not showing in admin result page - CU-2qhxf2

Fixed the css confict with email field - CU-3zurj6 f0f8c60

---

css/common.css
js/qsm-quiz.js

Fixed inconsistent font size in tablets and mobile devices for radio and checkbox label - CU-3zvmyp

Fixed NaN:NaN:NaN appears in the title - CU-41mpun

---

css/common.css
php/admin/settings-page.php
php/classes/class-qmn-quiz-creator.php
php/classes/class-qmn-quiz-manager.php

-Changed background option text
-Changed the layout of question_answer text for new quizzes

Fixed entire quiz was showing on load issue - CU-45khb0

---

mlw_quizmaster2.php
php/classes/class-qmn-quiz-manager.php
php/template-variables.php

- Changed the menu menu
- Fixed the file upload for new %QUESTIONS_ANSWERS_DEFAULT% template variable

- Moved the uploaded file into media menu

---

js/qsm-admin-emails.js
php/admin/options-page-email-tab.php
php/template-variables.php

Fixed the email tab not working issue

Made a common function for %QUESTIONS_ANSWERS% template

---

php/question-types.php
php/template-variables.php

Fixed icon was missing for last question in admin result page

Added support of title for captcha question type 

---

php/classes/class-qmn-quiz-manager.php
php/question-types.php

- Fixed the showing placeholder if the user does not answer when the comment field is enabled

- Fixed Scoring/Correct Answers not working for Apostrophe ( ' ) symbol

---

php/classes/class-qsm-questions.php

Inserting a link in the Correct info, new feature- #post-13646789

---

php/classes/class-qmn-quiz-manager.php

Inserting a link in the Correct info, new feature #post-13646789

---

css/common.css
js/qsm-quiz.js
php/admin/functions.php
php/admin/options-page-email-tab.php
php/admin/options-page-results-page-tab.php
php/classes/class-qsm-install.php
php/template-variables.php

Fixed social media sharing - #1qb39d

---

js/admin.js
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php
php/template-variables.php

Done feature request https://app.clickup.com/t/2hjptu

rounding the score feature

---

php/admin/functions.php
php/template-variables.php

full name fearure

---

php/admin/options-page-questions-tab.php
php/classes/class-qmn-quiz-manager.php

This feature allow hint section for support of anchot tag.

hint section anchor tag support

---

php/admin/admin-results-details-page.php
php/admin/options-page-questions-tab.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-install.php

Issue while assigning points with decimal value

assigning points with decimal value

---

php/admin/quiz-options-page.php
readme.txt

Added publish quiz button to publish the quiz - CU-1q7a4m

Et dev 7.2.0

---

js/qsm-quiz.js

I have created a new branch some issues occur during the push in the previously created branch.

issue resolved

---

php/template-variables.php

removed html decode causing error with rich text

---

php/rest-api.php

Fixed SQL Injection bug

---

css/admin-dashboard.css
css/qsm-admin.css
php/admin/addons-page.php
php/admin/functions.php
php/admin/quizzes-page.php
php/template-variables.php

fixed issues reported by sonarcloud

---

php/admin/options-page-style-tab.php
php/rest-api.php
php/shortcodes.php
php/template-variables.php

removed commented code

---

js/qsm-quiz.js

fixed time calculation only after form validates

---

css/qsm-admin-question.css
js/qsm-admin-question.js
php/admin/options-page-questions-tab.php

added functionality for soft delete and hard deletedeleting question deletes from database

---

js/qsm-quiz.js

adding mathjex on reload

---

php/admin/quizzes-page.php

esc_attr for paged parameter

---

php/classes/class-qmn-quiz-manager.php

fixed random questions not showing up

---

php/question-types.php
php/template-variables.php

fixed correct evaluation and formating of latex with anchor tag

---

php/classes/class-qmn-quiz-manager.php

enqeued neccesarry css for proper styling

---

php/classes/class-qmn-quiz-manager.php

adding dashicons to results shortcode

---

php/classes/class-qmn-quiz-manager.php

fixed social icons inactive on results page and shortcode

---

php/classes/class-qsm-install.php

Add action for extra option in quiz opitons

Justhyre aihr 5919

---

js/qsm-admin-question.js

Reverts QuizandSurveyMaster/quiz_master_next#1295

Revert "Added Richtext editor for Correct Answer Info - #219epr"

---

js/qsm-admin-question.js

Reverts QuizandSurveyMaster/quiz_master_next#1310

Added Richtext editor for Correct Answer Info - #219epr"

---

css/qsm-admin-question.css
js/qsm-admin-question.js
php/admin/options-page-questions-tab.php

Hiding correct answer info inside a button to avoid confusion between description textbox and correct answer textbox

Button to hide correct answer info

---

mlw_quizmaster2.php

Add isset condition to check facebook_app_id to avoiding undefined errors

add isset condition to check facebook_app_id

---

php/admin/quizzes-page.php

deleted quiz appears in search

---

js/qsm-admin-question.js
php/admin/options-page-questions-tab.php

polar for survey

---

php/admin/addons-page.php
php/admin/admin-dashboard.php

missing bundle icons

---

css/qsm-admin.css
js/admin.js
mlw_quizmaster2.php
php/admin/addons-page.php
php/admin/admin-dashboard.php
php/admin/functions.php
readme.txt

minor changes

---

php/question-types.php

mutiple fill in the blanks

---

css/qsm-admin.css

css changes

---

js/qsm-quiz.js

Reverts QuizandSurveyMaster/quiz_master_next#1387

Revert "fixed navigation issue with multiple quizzes on same page"

---

php/classes/class-qsm-install.php

Fixed the label for Question Per Category

---

css/qsm-admin.css

slack integration add new variables

---

php/admin/settings-page.php
php/classes/class-qmn-plugin-helper.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php
php/classes/class-qsm-settings.php
uninstall.php

Cu 4hd7rv global default setting for quiz option

---

mlw_quizmaster2.php
readme.txt

update new vaersion changelog

---

css/common.css
php/classes/class-qmn-quiz-manager.php
php/question-types.php
php/template-variables.php

Fill in the blank question type issue

---

php/template-variables.php

[QSM - Extra Template Variables] Emails look terrible  this - point done

---

php/classes/class-qsm-questions.php
php/template-variables.php

I fix in both  pages after completion of the quiz and the result page also

7x0d6a - %POLL_RESULT_X% issue while using Rich Answer or Image Answer

---

php/template-variables.php

As we discuss in the meeting revert commit and checking  with 4.7.1 after that take action

Cu 7hfkqu extra template variables emails look terrible -revert commit 

---

php/admin/settings-page.php

QA fail solve

---

php/template-variables.php

I change on multiple category  object

8zebe9 average category points x variable not working

---

php/classes/class-qsm-install.php
php/classes/class-qsm-settings.php

Fixes the issue with resetting to global settings on quiz options.

Cu bfeypn - preferred date format - set global options

---

js/qsm-admin-contact.js
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-contact-manager.php

A date type field has been introduced in the contact section. Output is converted to preferred date format before displaying.

Cu-3na9z3: date field for contact 

---

php/admin/admin-results-details-page.php
php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-manager.php

The qsm_generate_results_details_tab function has been refactored to convert admin results page date into preferred format.
Code for date conversion has been move to a function called convert_to_preferred_date_format under plugin helper.
Task Link: https://app.clickup.com/t/3na9z3

Cu-3na9z3 : date field for contact 

---

php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-questions.php
php/template-variables.php

- fixed issues with in_array() strict type matching 
- created common function to sanitize answer data during CRU operations 
- removed apostrophe and semi colon that was visible between comment form and hint
- fixed tick mark issue with fill in the blanks randomly

issues with survey form , comment box and fill in the blanks fixed

---

css/qsm-admin.css
js/qsm-admin.js
mlw_quizmaster2.php
php/admin/admin-results-page.php
php/admin/options-page-style-tab.php
php/admin/quiz-options-page.php
php/admin/quizzes-page.php
php/admin/tools-page.php
php/classes/class-qmn-quiz-creator.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-audit.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php

This is for audit page in which we included export and clear logs functionality.

Improvement in audit rashmi

---

php/template-variables.php

changes fixed in results page and quiz result.

Cu 1u4ug7n polar question with 10 input values rashmi singh

---

php/question-types.php
php/template-variables.php

Cu 1wuxhfa issue with fill in the blank

---

php/classes/class-qmn-quiz-manager.php
php/question-types.php
templates/qmn_primary.css

Fixed the multiple quiz shortcode issue and also with that UI issue.

Multiple Quiz Shortcode issue.

---

php/classes/class-qmn-quiz-manager.php
php/template-variables.php

Also while working on some task, I found some code without translation coding so I corrected them.

random fill in the blank question

---

php/template-variables.php

%CURRENT_DATE% format issue fixed.

Cu 1xhrhgq current date format issue fixed.

---

css/admin-dashboard.css
php/admin/admin-dashboard.php

Reverts QuizandSurveyMaster/quiz_master_next#1718

Revert "Cu 24bbvx4 word press 59 banner breaking qsm"

---

php/template-variables.php

advance question type addon hook

---

.github/pull_request_template.md
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-install.php

added option for change retake quiz button text #22hyjyp

---

php/classes/class-qmn-quiz-manager.php

Removed unnecessary code

---

php/classes/class-qsm-install.php

Fixed support link.

---

php/classes/class-qmn-quiz-manager.php

Added improvements for URL parameter addon

---

php/admin/admin-dashboard.php

solved php error with changelog #22xecb6

---

php/classes/class-qmn-quiz-manager.php
php/template-variables.php

Cu 22c51ha category score x variable not working

---

js/qsm-quiz.js

issue fixed with multiple quiz on single page

---

php/classes/class-qsm-install.php

removed text This option works only with Random Questions

---

php/classes/class-qmn-quiz-manager.php

Cu 232zt9d custom style template not working

---

php/admin/admin-results-details-page.php

Justhyre pinnacle 7798

---

js/qsm-quiz.js
php/classes/class-qmn-plugin-helper.php

Added jquery trigger and remove required properties

---

php/question-types/qsm-question-type-number.php
php/question-types/qsm-question-type-paragraph.php
php/question-types/qsm-question-type-polar.php
php/question-types/qsm-question-type-short-answer.php
php/template-variables.php

Fixed limit text issues.

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php

Fixed nonce issue.

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php

Reverts QuizandSurveyMaster/quiz_master_next#1792

Revert "Fixed nonce issue."

---

readme.txt

change log updated 7.3.13

---

php/classes/question-types/class-question-review.php
php/template-variables.php

Fixed line break issue.

---

mlw_quizmaster2.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-questions.php
readme.txt

Cu 23ec732 shortcode not working on elementor popup

---

php/classes/class-qmn-quiz-manager.php

Cu 23zptrj style template issue

---

php/template-variables.php

Cu 23m9021 the variables category score x and category points x don not work

---

php/classes/class-qsm-contact-manager.php

Added filter to change value of contact filed

---

php/classes/class-qsm-emails.php

issue fixed with Email template question number issue

---

css/common-rtl.css
css/common.css

fixed Polar question type responsive issue

---

css/qsm-admin-question-rtl.css
css/qsm-admin-question.css
js/qsm-admin.js
php/admin/options-page-questions-tab.php
php/rest-api.php

search question from question bank

---

js/qsm-quiz.js

issue fixed with elementor popup

---

css/qsm-admin-contact.css
js/qsm-admin.js
mlw_quizmaster2.php

touch device support added qsm edit quetion

---

mlw_quizmaster2.php
php/admin/options-page-questions-tab.php
php/admin/settings-page.php
php/classes/class-qsm-settings.php
readme.txt

changelog update 7.3.14

---

js/qsm-admin.js
mlw_quizmaster2.php
php/admin/admin-dashboard.php
php/admin/functions.php
php/admin/options-page-text-tab.php
php/admin/quizzes-page.php
php/admin/tools-page.php
php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-creator.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php
php/classes/class-qsm-questions.php

Added New hooks,
Added new quiz list,
Fixed quiz deletion with trash post,
Fixed edit quiz link in front-end.

Improvements and bug fixes

---

php/admin/quizzes-page.php

Fixed row action links.

---

php/admin/admin-dashboard.php

Display changelog from readme file instead of parsing script.

---

css/qsm-admin.css

Cu 25k793h improvements and bug fixes

---

php/classes/class-qsm-tracking.php

Fixed fatal error in usage tracking process.

---

js/qsm-quiz.js
mlw_quizmaster2.php
php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-manager.php

Cu 21fm2nk random questions

---

php/classes/class-qmn-background-process.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-emails.php

fixed issue with max input variable limit

---

php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-contact-manager.php
php/question-types/qsm-question-title.php
php/question-types/qsm-question-type-multiple-choice-horizontal.php
php/question-types/qsm-question-type-multiple-choice.php
php/question-types/qsm-question-type-multiple-response-horizontal.php
php/question-types/qsm-question-type-multiple-response.php
php/template-variables.php
php/template-variables/qsm-tempvar-question-answers.php

Fixed translation issues.

---

php/admin/settings-page.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php
php/classes/question-types/class-question-review-choice.php
php/classes/question-types/class-question-review.php

Cu 251z2d1 multiple correct answer issue

---

php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-creator.php
php/classes/class-qmn-quiz-manager.php
php/classes/question-types/class-question-review-choice.php
php/template-variables.php

Fixed tranlsation issues.

---

js/qsm-quiz.js
php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-manager.php

issue fixed with auto pagination

---

php/question-types/qsm-question-type-multiple-choice-horizontal.php
php/question-types/qsm-question-type-multiple-response.php

fixed issue with image type questions

---

php/question-types/qsm-question-title.php

Add filter 'qsm_after_question_title'

---

css/qsm-admin.css
php/classes/class-qmn-quiz-manager.php

fixed issue with correct score

---

css/qsm-admin.css
js/qsm-quiz.js
mlw_quizmaster2.php
php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-install.php
php/classes/class-qsm-migrate.php
php/classes/class-qsm-settings.php
php/datastore/class-qsm-data-store.php
php/legacy/class-qsm-legacy.php
php/models/class-question-model.php
php/models/class-quiz-model.php
php/models/class-results-model.php
php/models/index-models.php
php/qsm-core-functions.php
php/question-types/qsm-question-title.php
php/question-types/qsm-question-type-multiple-choice-horizontal.php
php/question-types/qsm-question-type-multiple-response.php

Cu 1x69p3x database restructure

---

readme.txt

Add insta wp demo master

---

php/admin/quiz-options-page.php
php/classes/class-qmn-quiz-creator.php

issue fixed with quiz title update

---

php/classes/class-qsm-contact-manager.php

Justhyre mgweb 7093

---

js/qsm-admin.js
js/qsm-quiz.js

fixed issue with timer

---

php/question-types/qsm-question-type-polar.php
php/question-types/qsm-question-type-text-or-html.php

Add Filter qmn_text_block_display

---

js/qsm-common.js

modified polar question selection

---

js/qsm-quiz.js
php/admin/settings-page.php
php/classes/class-qmn-quiz-creator.php
php/classes/class-qsm-install.php
php/template-variables/qsm-tempvar-question-answers.php

added option to show or not opt in type answers

---

php/classes/class-qsm-settings.php
php/template-variables/qsm-tempvar-question-answers.php

set default issue and hide result to everyone if opted

---

css/common.css
php/admin/quizzes-page.php
php/classes/class-qsm-contact-manager.php
php/template-variables/qsm-tempvar-question-answers.php

Cu 2c7ngyt undefined variable class

---

js/qsm-admin.js
php/admin/options-page-questions-tab.php
php/admin/quizzes-page.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-settings.php

Cu 2hxtgmq date column not sortable

---

readme.txt

Tested wp 6.0

---

js/qsm-admin.js
php/admin/options-page-questions-tab.php
php/classes/class-qmn-quiz-manager.php

Cu 2a22eqg issue with duplicate questions

---

php/classes/class-qsm-questions.php

fixed php warning

---

css/qsm-admin-rtl.css
css/qsm-admin.css
php/admin/quiz-options-page.php

Improved UI when multiple addons are active

---

css/qsm-admin-rtl.css
css/qsm-admin.css
php/admin/quiz-options-page.php

improve add-ons tabs UI

---

js/qsm-admin.js
php/admin/settings-page.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php

Cu 27xgxae split options page into sub sections

---

js/qsm-admin.js
php/admin/options-page-questions-tab.php

changes made in question list UI

---

css/qsm-admin-contact.css
css/qsm-admin-question.css
css/qsm-admin.css
js/qsm-admin.js
js/qsm-quiz.js
mlw_quizmaster2.php
php/admin/admin-dashboard.php
php/admin/options-page-contact-tab.php
php/admin/options-page-questions-tab.php
php/classes/class-qsm-contact-manager.php
templates/qmn_primary.css

Added new contact field types.

Added new contact field UI,

---

php/template-variables.php

fixed issue this html tags in answer fields

---

js/qsm-admin.js
php/admin/options-page-contact-tab.php
php/admin/options-page-text-tab.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php

Cu 2ewjv59 add an expandable link to view helpful docs

---

css/qsm-admin-rtl.css
css/qsm-admin.css
php/admin/quiz-options-page.php

add help section in quiz header

---

php/classes/class-qsm-emails.php

added qsm_results_css_inliner hook for customising email response

---

css/qsm-admin.css

Fixed input width issue.

---

php/classes/class-qsm-emails.php
php/classes/class-qsm-install.php

arrange quiz option

---

js/qsm-quiz.js
php/classes/class-qsm-contact-manager.php

Fixed validation issue for email field.

---

css/qsm-admin.css
php/admin/options-page-questions-tab.php
php/admin/quiz-options-page.php
php/classes/class-qsm-contact-manager.php

Fixed notices display issue. - #2gbcrfd

---

php/template-variables.php

Justhyre central course 8231

---

php/admin/options-page-questions-tab.php

fixed issue with manual pagination

---

php/admin/addons-page.php
php/admin/options-page-questions-tab.php
php/classes/class-qsm-install.php

Fixed bacward compatibility issue.

---

php/classes/class-qmn-log-manager.php

Fixed log manager issue.

---

php/admin/quiz-options-page.php

Removed addon icon from tab.

---

css/admin-dashboard.css
css/qsm-admin-rtl.css
css/qsm-admin.css
mlw_quizmaster2.php
php/admin/options-page-contact-tab.php
php/admin/options-page-questions-tab.php
php/admin/quiz-options-page.php
php/classes/class-qsm-contact-manager.php
php/classes/class-qsm-fields.php
php/question-types/qsm-question-type-opt-in.php
php/rest-api.php
php/template-variables/qsm-tempvar-question-answers.php

Fixed PHPCS & minor UI changes.

---

mlw_quizmaster2.php
readme.txt

version bump

---

php/admin/functions.php
php/classes/class-qmn-quiz-manager.php
php/question-types/qsm-question-title.php
php/question-types/qsm-question-type-multiple-choice-horizontal.php
php/question-types/qsm-question-type-multiple-choice.php
php/question-types/qsm-question-type-multiple-response-horizontal.php
php/question-types/qsm-question-type-multiple-response.php
php/question-types/qsm-question-type-opt-in.php
php/question-types/qsm-question-type-text-or-html.php
php/template-variables.php

Fixed content escaping issue.

---

mlw_quizmaster2.php
php/classes/class-qmn-quiz-manager.php

fixed issue with IOS devices

---

js/qsm-admin.js
php/admin/functions.php
php/admin/options-page-questions-tab.php
php/classes/class-qmn-quiz-manager.php
php/question-types/qsm-question-type-file-upload.php

Fixed question settings saving issue.

---

mlw_quizmaster2.php
readme.txt

update changelog to 8.0.2

---

js/qsm-admin.js

Fixed issue in question settings saving.

---

php/classes/class-qsm-emails.php
php/classes/class-qsm-results-pages.php

fixed issue with logic condition

---

php/classes/class-qsm-emails.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-results-pages.php

fixed issue with leaderboards template editor

---

php/admin/functions.php

Fixed theme path issue.

---

css/admin-dashboard.css
css/qsm-admin.css
js/qsm-admin.js
php/admin/functions.php
php/admin/options-page-style-tab.php
php/template-variables.php

add support for add images in theme customizer

---

js/qsm-quiz.js

added after page init hook

---

css/common.css
php/admin/quizzes-page.php
php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-creator.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-install.php
php/classes/class-qsm-migrate.php
php/classes/class-qsm-settings.php
php/template-variables.php

Added migration script to fix no. of questions.
Fixed no. of questions count.

Added migration script to fix no. of questions

---

js/qsm-quiz.js
mlw_quizmaster2.php
php/admin/admin-results-details-page.php
php/admin/settings-page.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-install.php
php/classes/class-qsm-migrate.php
php/classes/class-qsm-settings.php
templates/qmn_primary.css

Added option to disable MathJax.

---

php/classes/class-qmn-background-process.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-emails.php

fixed issue with %QUESTION_ANSWER_X% variable

---

css/qsm-admin-question.css
js/qsm-admin.js
php/admin/options-page-questions-tab.php
php/classes/class-qsm-questions.php
php/question-types/qsm-question-type-multiple-choice-horizontal.php
php/question-types/qsm-question-type-multiple-choice.php
php/question-types/qsm-question-type-multiple-response-horizontal.php
php/question-types/qsm-question-type-multiple-response.php

add option to set image size in image type answer

---

php/classes/class-qmn-quiz-manager.php

fixed issue with email function parameters

---

php/template-variables/qsm-tempvar-question-answers.php

added images size option on result page

---

php/admin/quiz-options-page.php
php/classes/class-qsm-install.php
php/classes/class-qsm-migrate.php

fixed issue with delete and duplicate quiz

---

php/classes/class-qsm-migrate.php

fixed issue with deleting quiz migration code

---

php/admin/options-page-contact-tab.php
php/classes/class-qsm-contact-manager.php

Justhyre deandre 6031

---

css/qsm-admin.css
php/admin/options-page-email-tab.php
php/admin/settings-page.php
php/classes/class-qmn-background-process.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-emails.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php
php/classes/class-qsm-settings.php

added send email option

---

php/classes/class-qsm-install.php

Added tooltip for disable mathjax option.

---

php/admin/options-page-email-tab.php
php/admin/settings-page.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-fields.php

fixed issue with save response setting

---

php/admin/functions.php
php/admin/options-page-email-tab.php
php/admin/options-page-results-page-tab.php
php/template-variables.php

Answer_x template variable is created

---

php/template-variables.php

Fixed full name variable issue.

---

css/qsm-admin-question.css
php/admin/options-page-questions-tab.php

images size input fields layout aligned

---

php/template-variables.php

comment is updated the Answer_x template variable is created

---

js/qsm-quiz.js
php/admin/functions.php
php/classes/class-qmn-quiz-manager.php

Cu 2u4vxw2 show quiz timer on load

---

js/qsm-quiz.js

fixed contact form hide issue

---

php/classes/class-qsm-contact-manager.php

fixed issue with checkbox field validation in quiz form

---

php/admin/admin-dashboard.php
php/admin/functions.php
php/admin/options-page-email-tab.php
php/admin/settings-page.php
php/classes/class-qmn-quiz-creator.php
php/classes/class-qsm-contact-manager.php
php/classes/class-qsm-tracking.php

Cu 2kbmh0v quiz wizard options

---

js/qsm-admin.js

add validation for polar questions

---

js/qsm-admin.js
mlw_quizmaster2.php
php/admin/admin-dashboard.php
php/admin/functions.php

Cu 2kbtx8d polar question show alert if points null

---

js/qsm-admin.js
php/admin/options-page-questions-tab.php
php/classes/class-qmn-quiz-manager.php
php/classes/question-types/class-question-review-fill-in-blanks.php
php/question-types/qsm-question-type-fill-in-the-blanks.php
php/template-variables.php

Cu 2gg5np4 case sensitive answer for fill in blank question

---

php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-manager.php

Fixed export result pdf issue.

---

css/common.css
js/qsm-admin.js
js/qsm-common.js
php/question-types/qsm-question-title.php
php/question-types/qsm-question-type-polar.php
php/template-variables.php

Cu 2kx1gge polar question image type issue

---

php/admin/options-page-questions-tab.php

typo change

---

php/admin/options-page-questions-tab.php

Fixed question option heading.

---

php/classes/class-qsm-contact-manager.php

Removed disabled contact fields from result array.

---

css/common.css

alignment of checkbox

---

php/admin/options-page-style-tab.php

Added checkbox input type option for theme customizer

---

js/qsm-quiz.js

Fixed auto scroll issue when option is disabled.

---

css/qsm-admin.css
php/admin/functions.php
php/admin/options-page-style-tab.php

show all theme in style tabs

---

php/admin/functions.php
php/classes/class-qsm-theme-settings.php

fixed isse with already installed plugin data

---

php/question-types/qsm-question-type-multiple-choice-horizontal.php
php/question-types/qsm-question-type-multiple-response-horizontal.php

hook added for horizontal choice question css

---

js/qsm-common.js

resolved issues with images on moving the polar slider

---

php/question-types/qsm-question-type-multiple-choice-horizontal.php
php/question-types/qsm-question-type-multiple-response-horizontal.php

add hook parameter for answer loop hook

---

css/common.css
php/template-variables/qsm-tempvar-question-answers.php

image caption display on the admin results and front end results

---

php/question-types/qsm-question-type-opt-in.php

Cu 2rhpx1a opt in question type display blank checkbox

---

templates/qmn_primary.css

Cu 2rhneh0 spacing at the bottom of the welcome page

---

php/question-types/qsm-question-type-opt-in.php
php/template-variables/qsm-tempvar-question-answers.php

Cu 3duverr alignment of answers

---

php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-theme-settings.php

undefined error on deactivating the theme

---

js/qsm-admin.js
php/classes/class-qmn-quiz-manager.php

fixed issue with span entry with 0 second time

---

php/classes/class-qmn-quiz-manager.php

removed recaptcha code and moved to addon

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php
php/template-variables.php

fixed issue with advance timer

---

js/qsm-admin.js

Fixed questions loading issue.

---

js/qsm-quiz.js

Cu 2tttk3z spam in result

---

js/qsm-quiz.js

fixed issue with recaptcha

---

css/qsm-admin.css
php/admin/functions.php
php/admin/quiz-options-page.php
php/admin/quizzes-page.php
php/classes/class-qsm-theme-settings.php

Added minor changes related to UI and fixed PHPCS issues.

---

readme.txt

change log updated

---

css/common.css
php/question-types.php
php/question-types/qsm-question-type-number.php
php/template-variables.php
templates/qmn_primary.css

issue fixed with QSM 8.0.4

---

js/qsm-quiz.js
php/question-types/qsm-question-type-number.php

fixed issue with maxlengh

---

php/admin/admin-results-page.php
php/admin/functions.php

Fix wordings.

---

readme.txt

Updated release date.

---

php/template-variables.php
php/template-variables/qsm-tempvar-question-answers.php

Fixed empty lines in result pages.

---

js/qsm-admin.js

added a trigger for the flashcard addon

---

php/admin/functions.php
php/classes/class-qmn-quiz-manager.php

Fixed file upload warning issue.

---

js/qsm-quiz.js
mlw_quizmaster2.php
templates/qmn_amethyst.css
templates/qmn_base.css
templates/qmn_emerald.css
templates/qmn_gray.css
templates/qmn_primary.css
templates/qmn_turquoise.css

Fixed validation message for contact fields.

---

php/classes/class-qmn-quiz-manager.php

Added message to display when quiz is deleted.

---

php/admin/about-page.php
php/admin/addons-page.php
php/admin/admin-dashboard.php
php/admin/admin-results-page.php
php/admin/functions.php
php/admin/options-page-questions-tab.php
php/admin/quiz-options-page.php
php/admin/quizzes-page.php
php/classes/class-qsm-install.php

Added new UTM Parameters.

---

css/qsm-admin.css
js/qsm-admin.js
php/admin/options-page-text-tab.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php

new text tab ui changes

---

php/admin/options-page-text-tab.php
php/classes/class-qmn-plugin-helper.php
php/template-variables.php

fixed issue with random answer

---

js/qsm-quiz.js
php/classes/question-types/class-question-review-file-upload.php
php/classes/question-types/class-question-review.php
php/question-types/qsm-question-type-file-upload.php
php/question-types/qsm-question-type-number.php
php/template-variables.php

Fixed security issues.

---

css/admin-dashboard.css
css/qsm-admin.css
js/qsm-admin.js
php/admin/admin-dashboard.php
php/admin/functions.php
php/admin/options-page-style-tab.php
php/classes/class-qmn-quiz-manager.php

Cu 1ye63x7 qsm pro themes

---

css/qsm-admin.css
js/qsm-admin.js
php/admin/options-page-text-tab.php
php/classes/class-qsm-fields.php
php/classes/class-qsm-install.php

Revert new text tab UI

---

css/qsm-admin-question.css
js/qsm-admin.js
php/admin/options-page-questions-tab.php
php/rest-api.php

added search by category option

---

css/common.css
css/qsm-admin.css
js/qsm-admin.js
mlw_quizmaster2.php
php/admin/options-page-questions-tab.php
php/admin/quiz-options-page.php
php/admin/quizzes-page.php
php/classes/class-qmn-plugin-helper.php
php/classes/class-qmn-quiz-manager.php
php/question-types.php
templates/qmn_primary.css

Cu 2vk28qv question type deactivation error

---

php/classes/class-qmn-quiz-manager.php

added classes and id for the retake button

---

php/admin/options-page-questions-tab.php
php/admin/quizzes-page.php

CU-3q4e4gg - fixed database error.

---

php/classes/question-types/class-question-review-fill-in-blanks.php

Fixed the french accents

---

css/qsm-admin.css

alignment and line height issue fixed

---

php/admin/options-page-text-tab.php

updated the changes

---

css/qsm-admin.css
js/qsm-admin.js
php/admin/options-page-text-tab.php

added a label select label

---

js/qsm-admin.js
php/admin/options-page-text-tab.php

fixed the bugs

---

js/qsm-quiz.js

fixed issue with timer js

---

css/qsm-admin.css
js/qsm-admin.js
php/admin/options-page-text-tab.php
php/classes/class-qsm-fields.php

Alignment of the custom label menus

---

php/classes/question-types/class-question-review-text.php
php/template-variables.php

fixed issue with german letters

---

php/backward-compatibility/qsm-backward-compatibility-template-variables.php
php/template-variables.php

Fixed image size issue in result page.

---

js/qsm-admin.js
php/admin/options-page-questions-tab.php
php/classes/class-qsm-questions.php

Added hooks to extend functionality.

---

css/qsm-admin-question.css
js/qsm-admin.js
php/admin/options-page-questions-tab.php

Added UI improvements.

---

php/question-types.php

Rename option label.

---

mlw_quizmaster2.php
php/admin/options-page-text-tab.php
php/admin/quiz-options-page.php
php/admin/quizzes-page.php
php/classes/class-qsm-fields.php
readme.txt

fixed phpcs and update changelog

---

css/admin-dashboard.css
mlw_quizmaster2.php
php/admin/admin-dashboard.php
php/admin/admin-results-page.php
php/admin/quiz-options-page.php
php/admin/quizzes-page.php

user role addon hooks added

---

js/qsm-quiz.js

disabled the submit button on uploading and enable after uploaded

---

blocks/block.js
blocks/block.php

fix block editor dep notices #1945

---

css/admin-dashboard-rtl.css
css/admin-dashboard.css
js/qsm-quiz.js
php/admin/admin-dashboard.php
php/admin/functions.php

match timer issue

---

js/qsm-quiz.js

fixed required issue with logic addon

---

php/admin/admin-dashboard.php
php/admin/quizzes-page.php
php/admin/settings-page.php
php/classes/class-qsm-install.php
php/classes/class-qsm-settings.php
php/question-types.php
php/question-types/qsm-question-type-opt-in.php
php/template-variables.php

Cu 3d3byxk display text html section result page

---

php/question-types/qsm-question-type-opt-in.php
php/template-variables.php

fixed issue with html question

---

js/qsm-quiz.js

match pagination animation

---

php/admin/functions.php
readme.txt

update release date

---

php/admin/options-page-text-tab.php

Cu 326qwh3 error in quiz text tab

---

php/template-variables.php

fixed issue with short answer

---

js/qsm-admin.js
php/admin/options-page-text-tab.php

fixed Vulnerability report

---

js/qsm-admin.js

condition given for the flashcard

---

mlw_quizmaster2.php
readme.txt

update changelog to 8.0.8

---

php/template-variables.php

Cu 333bktb rich and image answers not working advance question type

---

css/qsm-admin.css
php/admin/functions.php
php/admin/options-page-style-tab.php

added option for input control

---

php/admin/functions.php
php/question-types/qsm-question-title.php

fixed conflict with the post grid plugin

---

readme.txt

update instawp.io to instawp.com

---

php/classes/class-qmn-plugin-helper.php

add space in wrong answer text in email

---

php/classes/class-qmn-quiz-manager.php

hook for advanced question type

---

css/common.css
css/qsm-admin.css

Removed !important from the files

---

js/qsm-quiz.js

advance question type validation

---

css/qsm-admin.css
php/admin/options-page-questions-tab.php

Change Document Links

---

js/qsm-admin.js

duplicating issue on moved new question to new page

---

css/qsm-admin.css
js/qsm-admin.js
php/admin/options-page-questions-tab.php

Add change order option for questions

---

php/classes/class-qmn-quiz-creator.php

bug fixing while deleting the quiz

---

css/qsm-admin.css
js/qsm-admin.js
php/admin/options-page-questions-tab.php

Fixed page deletion move issue

---

php/admin/admin-results-page.php

Add filter 'qsm_results_quiz_name_class'

---

css/qsm-admin.css
js/qsm-admin.js
php/admin/options-page-questions-tab.php

change error message position and reset old code

---

js/qsm-quiz.js

timer minutes issue is fixed

---

php/classes/class-qmn-quiz-manager.php

Cu 85zrh2752 separate start quiz button

---

php/admin/admin-dashboard.php
php/classes/class-qsm-settings.php

fixed issues while creating quiz setting

---

css/qsm-admin.css
js/qsm-admin.js
php/admin/options-page-email-tab.php
php/admin/options-page-results-page-tab.php

upgrade option added with the messagein email and results tab

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php

fixed Security Vulnerabilities

---

js/qsm-quiz.js

timer issue initial

---

js/qsm-quiz.js

Fix extra next button in contact form

---

js/qsm-admin.js

Fixed hide show options while switch quiz-type

---

js/qsm-quiz.js

timer minutes issue fixed

---

js/wp-color-picker-alpha.min.js
mlw_quizmaster2.php
php/admin/functions.php
php/admin/options-page-style-tab.php

added transparent option in color picker

---

js/qsm-admin.js
php/admin/options-page-questions-tab.php

duplicate question the move button fix

---

css/common.css
js/qsm-quiz.js

added css for popup

---

php/question-types/qsm-question-type-polar.php
templates/qmn_primary.css

fixed required fields in polar type questions

---

php/question-types/qsm-question-title.php

featured image setting

---

css/qsm-admin.css
mlw_quizmaster2.php
php/admin/quiz-options-page.php
php/admin/tools-page.php

Cu 85zrmc0k6 improve import export

---

php/admin/functions.php

updated code

---

php/template-variables.php

paragraph question type no space inbetween the words for wrong answer

---

css/common.css
php/question-types/qsm-question-title.php
php/question-types/qsm-question-type-fill-in-the-blanks.php

Cu 85zrmerd3 breeze theme issues

---

css/qsm-admin-question.css
php/admin/options-page-email-tab.php
php/admin/options-page-questions-tab.php
php/admin/options-page-results-page-tab.php

added hooks for advance assessment addon

---

js/qsm-admin.js

fixed issue with add question button js

---

css/common.css
js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php

fixed issue with inline result for short answer

---

js/qsm-quiz.js

fixed quizID error

---

php/admin/settings-page.php
php/classes/class-qsm-install.php
php/template-variables/qsm-tempvar-question-answers.php

added one option for hide correct answer after quiz submited

---

php/template-variables.php

Cu 85zrnfe1v incorrect correct class issue

---

php/classes/class-qmn-plugin-helper.php

minor changes in email inline css

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php
php/template-variables.php
templates/qmn_primary.css

added new class for show inline option question setting.

---

js/qsm-quiz.js

fixed issue with correct in correct class

---

css/common.css
templates/qmn_primary.css

mobile-version-button-overlap-issue

---

php/template-variables.php

fixed issue with encoding

---

php/classes/class-qsm-emails.php

fixed issue with reply to email

---

js/qsm-quiz.js

fixed issue with submit quiz logic if answer is wrong

---

js/qsm-quiz.js

fixed submit if ans wrong issue with manual pagination

---

css/common.css
js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php
templates/qmn_primary.css

Fix next and previous button mobile device

---

templates/qmn_primary.css

Minor changes for space between buttons

---

php/admin/admin-results-details-page.php
php/classes/class-qmn-quiz-manager.php

hook added for admin result page

---

templates/qmn_primary.css

minor changes in css for button

---

mlw_quizmaster2.php
readme.txt

update changelog 8.1.1

---

php/classes/class-qmn-quiz-manager.php

fixed submit button issue

---

mlw_quizmaster2.php
readme.txt

update changelog 8.1.2

---

js/qsm-admin.js

fix the jquery error

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-emails.php

hook added for user activity

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-emails.php

fixed submit button text issue

---

php/template-variables.php

The score does not display in round-off

---

js/qsm-admin.js
js/qsm-quiz.js
php/admin/options-page-contact-tab.php
php/classes/class-qmn-quiz-manager.php
php/classes/class-qsm-contact-manager.php
php/classes/class-qsm-emails.php
templates/qmn_amethyst.css
templates/qmn_base.css
templates/qmn_emerald.css
templates/qmn_gray.css
templates/qmn_primary.css
templates/qmn_turquoise.css

Cu 85zrpqmpa contact form additional type fields

---

js/qsm-quiz.js
php/classes/class-qmn-quiz-manager.php

fixed issue with submit buttons

---

js/qsm-quiz.js

Fixed contact form checkbox validation
